### ISSUE TITLE
FounderHub DesignQA adjustments

### ISSUE THREAD

**Issue by vanessadespain** [near/near-discovery#1020]
Laura asked me to help with design improvements to the latest iteration of the [FounderHub](https://near.org/founders). 

I've created a Figma page to outline the changes on the current live page and provided a design to show the desired changes implemented. 

Figma link: [here](https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=692-11016&mode=design)

This image shows the current page with the feedback for changes: 
![image](https://github.com/near/near-discovery/assets/8346374/4df6af6e-faab-45cf-b35e-3901e9572091)
1. Center align the "Welcome to Near..." text block
2. Move the subheadline copy, "Tap into our curated resources..." to be just beneath the section title "Self Serve Resources"
3. Move the subheadline copy, "Find your place within the ecosystem..." to be just beneath the section title "Ecosystem Community Resources"
4. Shorten the copy, "Find your place within the ecosystem..." to: "Find your place within the ecosystem — your community is near."
5. The Accelerate your Web3 Journey section should adopt the layout of “Content with Image” available on the Ecosystem overview page. Add the image in the designs to this page. I've uploaded the image to [Drive](https://drive.google.com/file/d/16qpYf8DzeIz2haBWbvWPTpJ0LXY5wHcA/view?usp=drive_link). 
6. Change "Get in touch" section to green background. 
7. Change copy of "Get in touch" section to: Headline, "Get in touch" (42px medium) and subheadline, "Reach out to us to provide your feedback or to ask for specific support." (20px regular)
8. Remove section "The OS for an open web"

The image below shows the desired design: 
![image](https://github.com/near/near-discovery/assets/8346374/92d20b52-abb3-447c-bd62-404b4c88b20d)

Please ping @vanessadespain with any follow-up questions

**Comment by LCCCunningham** [comment]
Hey @shelegdmitriy @charleslavon  - checking in on progress here. LMK when it's ready to review - we are eager to push out to the community. Thanks!

**Comment by shelegdmitriy** [comment]
Hey @LCCCunningham I'll ping you very soon

**Comment by shelegdmitriy** [comment]
@LCCCunningham it's done. Is is worth to promote into production today of we can wait for the regular release?

**Comment by vanessadespain** [comment]
@shelegdmitriy Is there a staging link we can review before it's pushed live?

**Comment by shelegdmitriy** [comment]
> @shelegdmitriy Is there a staging link we can review before it's pushed live?

Unfortunately no. But it's already in production so feel free to create a new task if there is something I can improve

**Comment by vanessadespain** [comment]
Thank you! Will do
