### ISSUE TITLE
404 Error For NEAR Whitepapers that need redirects

### ISSUE THREAD

**Issue by s-n-park** [near/near-discovery#1030]
**Describe the bug**
The URL https://near.org/papers/the-official-near-white-paper, which is supposed to lead to the official NEAR Protocol white paper, results in a 404 error (page not found). This link has been extensively referenced externally, with 2,232 links pointing to it, including major platforms like CoinMarketCap.

**To Reproduce**
1. Go to any website that references the NEAR Protocol white paper, such as [CoinMarketCap](https://coinmarketcap.com/currencies/near-protocol/).
2. Click on the link that is supposed to take you to the white paper.
3. The browser attempts to navigate to https://near.org/papers/the-official-near-white-paper.
4. A 404 error page is displayed, indicating that the requested page could not be found.

**Expected behavior**
Clicking on the link should lead to the download page or display the NEAR Protocol white paper directly. The expected URL for the white paper is https://near.org/files/white-paper-near-protocol.pdf

We should also do the same for the other papers:
https://near.org/papers/nightshade -> https://near.org/files/nightshade.pdf
https://near.org/papers/doomslug -> https://near.org/files/doomslug.pdf
https://near.org/papers/economics-in-sharded-blockchain -> 404 (seems like this is deprecated?)

**Screenshots**
![image](https://github.com/near/near-discovery/assets/146785798/ac639460-fbc5-4f03-af68-4cc113c32419)
![image](https://github.com/near/near-discovery/assets/146785798/8b75e3aa-847c-4256-b6f7-c59e2e5d839a)

**Additional context**
This URL was the 2nd most referenced link for the NEAR Protocol externally as of a few weeks ago. The significant number of external references to this URL indicates that it's a critical link for individuals seeking information about the NEAR Protocol.

Original PR: https://github.com/near/near-discovery/issues/968

**Comment by shelegdmitriy** [comment]
@s-n-park I added a proper redirect for https://near.org/papers/the-official-near-white-paper. 

> https://near.org/papers/nightshade
> https://near.org/papers/doomslug

Will work after release (today)

> https://near.org/papers/economics-in-sharded-blockchain 

There was no such document in the original task, so we need to get that doc and upload to make it accessible on near.org

**Comment by shelegdmitriy** [comment]
cc @charleslavon
