### ISSUE TITLE
🔷  Redirect these  high-trafficked, older links & blog posts to more relevant content

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1034]
## What ?

- **High Level Goal:**

Improve the relevancy of [incoming traffic from google search results](https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Fnear.org%2F&hl=en&breakdown=page) by replacing the following links with blog posts of updated content. 

- https://near.org/blog/near-token-supply-and-distribution
- https://near.org/blog/near-wallet-update-staking-and-withdrawing-tokens
- https://near.org/about/network/validators
- https://near.org/about
- https://near.org/blog/staking-rewards-are-live
- https://neartasks.ai/taskers

**Comment by s-n-park** [comment]
I can help pull an updated list of pages for whenever this gets picked up, for example:
https://near.org/blog/near-announces-the-blockchain-operating-system/

is still pretty popular landing page.
