### ISSUE TITLE
BOS UI search bar, notifications, and profile icon component(s)

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1050]
Do we need to refactor the search component? That dropdown has a log going on

- we probably want to rip out the nextjs search input, so that the entire UI is based on vm components

**Comment by calebjacob** [comment]
Hey @shelegdmitriy, here's a link to the Figma: https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=757-19342&mode=design&t=gsQu6etNp5y0UUzu-0

I took a screenshot and highlighted the components this ticket should be focused on:

<img width="1206" alt="Screen Shot 2024-03-11 at 11 10 51 AM" src="https://github.com/near/near-discovery/assets/1475067/75f7a6ab-0b76-410f-a841-10c878100023">

Notice how we'll probably need to build out separated BOS components (the blue outlines) that can be rendered individually based on large screen vs mobile designs.

The red outline could also be a BOS component that's used specifically for larger screens. Maybe it's called `LargeScreenHeader` or something.

**Comment by calebjacob** [comment]
Something else to note @shelegdmitriy:

I'm planning on deleting the current `Navigation` component/folder in a feature branch I'm working on for the new sidebar layout. I'd say focus this ticket on only building/extracting the highlighted BOS components. Once we've both made more progress, we can figure out how to integrate your new BOS components into the Next JS layout.

**Comment by calebjacob** [comment]
Hey @shelegdmitriy, not sure if you saw the latest changes in Figma, but here's the latest mobile design:

<img width="494" alt="Screen Shot 2024-03-13 at 3 36 22 PM" src="https://github.com/near/near-discovery/assets/1475067/611e1f6a-77c5-4b59-9063-c31ba268b98e">

The mobile design now has the notification button dropdown just like on larger screens. For mobile, the search icon will actually just be a button that takes you to our search page.

I'm thinking this could make this most sense now:

1. Let's create a BOS Component for `LargeScreenHeader` (feel free to change the name) that would build the area highlighted in blue here:

<img width="1109" alt="Screen Shot 2024-03-13 at 3 39 57 PM" src="https://github.com/near/near-discovery/assets/1475067/d4a4e816-d6d9-44c8-a438-6426d78f6142">

2. Build another BOS Component for `SmallScreenHeader` that would build the area highlighted in blue here for smaller screens (the NEAR logo and hamburger menu icon will be rendered by my new layout work in Next JS): 

<img width="494" alt="Screen Shot 2024-03-13 at 3 36 22 PM" src="https://github.com/near/near-discovery/assets/1475067/1642971a-06d3-42e7-bda2-964f8b7941cd">

Let me know if you have any questions or thoughts. Thanks! :)

**Comment by calebjacob** [comment]
I just realized we're missing Figma designs for the `logged out` state it seems. @vanessadespain, would you be able to point us toward designs for how we're wanting the logged out version to look for desktop and mobile?

**Comment by shelegdmitriy** [comment]
Hey @calebjacob! I started to work of this a bit late (yesterday actually). I'll try to submit a PR with this components today

**Comment by calebjacob** [comment]
Hey @shelegdmitriy, so there has been a plot twist I wasn't initially aware of. It shouldn't impact your work though. When a user hasn't signed in yet, we are actually going to still display the current/old navigation as is. We'll only render this new layout when a user is signed in.

So this simply means I won't be deleting the current `Navigation` component folder (I'll just be renaming it and moving it).

The updated sidebar layout will use your updated BOS components only when the user is signed in (for now).

Hopefully that context helps.

**Comment by shelegdmitriy** [comment]
> Hey @shelegdmitriy, so there has been a plot twist I wasn't initially aware of. It shouldn't impact your work though. When a user hasn't signed in yet, we are actually going to still display the current/old navigation as is. We'll only render this new layout when a user is signed in.
> 
> So this simply means I won't be deleting the current `Navigation` component folder (I'll just be renaming it and moving it).
> 
> The updated sidebar layout will use your updated BOS components only when the user is signed in (for now).
> 
> Hopefully that context helps.

Thanks @calebjacob !
