### ISSUE TITLE
NextJS based left-hand navigation

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1051]

**Comment by calebjacob** [comment]
After talking with Charles, we decided it makes sense to move the `Pinned Apps` to a future scope. So that will be out of scope for this ticket.

**Comment by vanessadespain** [comment]
[Figma Design Link](https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=755-11330&mode=design)

![image](https://github.com/near/near-discovery/assets/8346374/912963e2-5d5c-4766-81a3-1936a853dc35)
<img width="1071" alt="image" src="https://github.com/near/near-discovery/assets/8346374/b737b87f-b73c-4d40-9ae2-66af1cc2a223">

Still work in progress on the pages: Home and Activity for MVP

**Comment by vanessadespain** [comment]
Resources Links: 

[Documentation](https://docs.near.org/) 
~~Earn & Contribute~~ [Get Funding](https://near.org/ecosystem/get-funding)
[Careers](https://careers.near.org/)
[Support](https://pages.near.org/about/contact-us/) - Currently going to a Wordpress page, I think this will be updated soon
More --> Opens submenu containing of the Marketing Nav links

@charleslavon Would you double check me on this?

**Comment by charleslavon** [comment]
@vanessadespain for [an improved contact us page](https://github.com/near/near-discovery/issues/1064)

**Comment by vanessadespain** [comment]
Improving on the interaction states for the navigation
[Prototype](https://www.figma.com/proto/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?page-id=755%3A11330&type=design&node-id=788-10896&viewport=1713%2C416%2C0.38&t=px6dmXA0SzddWoYP-1&scaling=min-zoom&starting-point-node-id=788%3A10896&mode=design) | [Design Link](https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=902%3A22917&mode=design&t=wMRhE1UovKLYukwq-1)

![image](https://github.com/near/near-discovery/assets/8346374/98101b85-8fb1-4a05-93aa-f6b9e801b86e)


I'd love to spend a little time thinking/prototyping how we could make the secondary nav less intrusive and/or allow it to be collapsed. One idea from the [material.io](https://m3.material.io/components) side bar is to only show the secondary nav on hover, however I'm not confident that this would be a good solution for us so I'd like to experiment a bit.
