### ISSUE TITLE
Link Events on Homepage to pull in data from new Events page

### ISSUE THREAD

**Issue by vanessadespain** [near/near-discovery#1060]
Currently the near.org logged-out homepage pulls in events data. Can we update the feed here to pull in the latest from the new Events page?

Currently it's showing past events:
![image](https://github.com/near/near-discovery/assets/8346374/b09d1722-1db5-4d58-8cf1-cfe31d419e94)

**Comment by charleslavon** [comment]
@vanessadespain do you want it to only show upcoming events? Currently there is only one event so it would have just one square tile like this page - https://near.org/events. Or should we show upcoming and recent events?
