### ISSUE TITLE
Careers Page navigation, account, and footer

### ISSUE THREAD

**Issue by vanessadespain** [near/near-discovery#1065]
Can we make the Careers page use the global navigation? 
- It appears to use its own version or a previous version of the navigation. 
- Some of the links in this navigation are broken.
- The Create Account button goes to the wallet page.
- Perhaps consider moving from careers.near.org to near.org/careers? 
- The footer looks to be from 2022

![image](https://github.com/near/near-discovery/assets/8346374/a49c5cd3-0bca-429a-a23b-43073a643616)
![image](https://github.com/near/near-discovery/assets/8346374/b4cfe279-d8fc-487f-aa4a-2bfae46fa224)

**Comment by charleslavon** [comment]
@vanessadespain this is it's own site and nav. There's probably a team at NF that manages/managed this. Maybe we can find someone to support updating this.
