### ISSUE TITLE
Enhancement: subscribe newsletter click event

### ISSUE THREAD

**Issue by s-n-park** [near/near-discovery#1068]
**Describe the Enhancement**
When clicking on subscribe in Newsletter on blog we'd like for this to trigger a Rudderstack click event. This was a request from the NF marketing team who would like to understand the % of near.org website visitors that sign up for the newsletter.

**To Reproduce**
1. Go to near.org/blog
2. Open developer tools
3. Scroll to bottom of page
4. Enter email
5. Click subscribe

**Requested behavior**
Would hope to see a Rudderstack click event triggered

**Screenshots**
![image](https://github.com/near/near-discovery/assets/146785798/39441278-ac63-4242-8351-5e78507fe128)

**Desktop (please complete the following information):**
 - OS: Macbook
 - Browser Chrome
 - Version: Version 122.0.6261.112

**Comment by s-n-park** [comment]
FYI: @charleslavon - didn't assign since I'm waiting to hear from NF how much of a priority this is (marked as enhancement)

**Comment by charleslavon** [comment]
This need needs to be accomplished another way. This page is static html exported from wordpress and trying to enhance that codebase is a pandora's box that I don't want to open. 

Can you look at the page view data for `/blog` to get the denominator and reach out to nearweek to get the numerator (total subscribed users)?

**Comment by s-n-park** [comment]
@charleslavon - haha yea I figured there was something funky going on under the hood thanks for the heads up but wanted to check in case it was easy. Definitely de-pri since ya'll are busy with the migration
