### ISSUE TITLE
Feature Request: Implement updates to NEAR Horizon Accelerator landing page 

### ISSUE THREAD

**Issue by jbarnes850** [near/near-discovery#1075]
---
|   Section      |           Request                     |
|---------------|------------------------------------------------------|
| **Label**      | Feature request                                      |
| **Request**     | Implement updates to NEAR Horizon Accelerator landing page |
---

## Background
The NEAR Horizon Accelerator landing page does not currently reflect the latest information for the upcoming cohorts, and some of the program benefits have been updated. 

The Founder Success team requires the landing page to be revised based on the recommended changes detailed below. This includes text updates in the Hero and FAQ sections, the removal of specific program benefits, and the addition of a new banner on the near.org landing page.

**Changes Required:**

1. **Top Banner:** Remove the “Explore Horizon” button.
   - [HZNNav.astro](https://github.com/near-horizon/horizon/blob/dev/web/src/layouts/HZNNav.astro)
2. **Hero Section:** Update the text to “Next Cohort Starts in May 2024. Apply now!”
   - [Hero.astro](https://github.com/near-horizon/horizon/blob/dev/web/src/components/hzn/Hero.astro)
3. **[Program Benefits Section](https://github.com/near-horizon/horizon/blob/dev/web/src/components/hzn/Comprehensive.tsx):**
   - Remove the “Earn Horizon Credits” box.
   - Remove the “Access to a Vetted Marketplace” box.
   
4. **FAQs:**
- Update Question: “What is NEAR Horizon?”
New Answer: “NEAR Horizon (HZN) is an equity-free accelerator program for web3 Founders. HZN facilitates three cohorts annually with batches of 15-20 Founders per cohort, ranging from idea-stage to seed stage. Founders will receive mentorship, 1:1 technical support, and tactical education on how to scale a project - all equity free. HZN has 50+ alumni projects like Gravvity, Quest, Plato, Shard Dog, Contented and Solaire that have gone on to raise over $20M in combined external capital.”
- Update Question: “When does the cohort start?”
New Answer: “We offer three cohorts per year. Cohorts begin in January (Winter), May (Summer), and October (Fall). Applications are open year-round, with each cohort having specific application deadlines. Please refer to the application for information on the specific deadline based on the cohort you are applying for.”
File location: FAQ.astro

5. **Near.org Landing Page:**
   - Add a new banner with the tagline “Are you an early-stage founder? Apply to our equity-free accelerator program. Applications are now live!” and an "Apply Now" button. Apply Now = https://airtable.com/appFoIqAoY0ikoVIb/shrst8Tt4PUtYTSvD

**Additional context**
Find the current live page for reference [here](https://www.hzn.xyz/hzn).
Also, please find the attached screenshots from the design file which highlight the specific changes needed.
![Screenshot 2024-03-18 at 3 46 03 PM](https://github.com/near/near-discovery/assets/104687165/ce9e9128-3c37-441d-a107-2233ba590f93)
![Screenshot 2024-03-18 at 3 46 09 PM](https://github.com/near/near-discovery/assets/104687165/665dde38-06cc-4a76-9b66-b2b8db205da7)
![Screenshot 2024-03-18 at 3 46 20 PM](https://github.com/near/near-discovery/assets/104687165/47ced1bb-1ee7-4ccc-8aba-e4a8b8b0ad1e)
![Screenshot 2024-03-18 at 3 47 05 PM](https://github.com/near/near-discovery/assets/104687165/24313ea8-629d-4e4e-b010-0c6473b03fee)

**Comment by charleslavon** [comment]
@shelegdmitriy  This issue is requesting changes to the [hzn repo](https://github.com/near-horizon/horizon/app). Specifically the 'app' package.  Similar to our gateway, it is setup via vercel to auto deploy on merges to main.

**Comment by shelegdmitriy** [comment]
Oh, nevermind. Seems like this [link](https://github.com/near-horizon/horizon/app) has been broken
