### ISSUE TITLE
Improve NearSocial blogs by setting the header image as an ipfs file attachment

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1094]
**Why**
When clicking the `Copy URL to clipboard` option of a NearSocial post and pasting it on another platform like slack, or twitter, a call is made to fetch the post's metadata to show it in a thumbnail preview.  For a regular near social posts like [this one](https://near.org/s/p?a=cesinha667.near&b=115229395) that preview includes an image. 
<img width="662" alt="Screen Shot 2024-03-27 at 8 45 51 AM" src="https://github.com/near/near-discovery/assets/1915116/cd9c77bc-d4bb-4c58-9aa7-8f7ad9a82b76">

When clicking the `Copy URL to clipboard` option of a near blog post like  [this one](https://near.org/near/widget/BlogPostPage?accountId=near&blockHeight=114529294). No thumbnail is generated at all, because this share URL does not use the s/p route which maps to [our gateway's metadata fetch route](https://github.com/near/near-discovery/blob/752a04f8db856f93b6721159e80ab03c3f52d1c5/src/pages/s/%5BurlShareIndicator%5D.tsx#L67).   Also, if you try to use manually create the same `s/p` style route for a near blog post, the default `near-meta.png` from near.org is used because the call to fetch the post's metadata does not return any of the images included in the actual post.
<img width="702" alt="Screen Shot 2024-03-27 at 8 47 18 AM" src="https://github.com/near/near-discovery/assets/1915116/701b4d5c-df31-4c2a-acce-94cfcdf00638">

These are the two api calls for the above post metadata images: 

1. https://api.near.social/get?keys=cesinha667.near/post/main&blockHeight=115229395
2. https://api.near.social/get?keys=near/post/main&blockHeight=114529294

**Describe the solution you'd like**
Ideally, for a more robust near social blog feature, the metadata for near blog posts would include the ipfs_cid of the blog's header image. What would be the cost (on the UX of creating a post, and dev effort) to resolve this? If we update the share URL of near blog posts, we would also need to consider how to ensure that a blog post's header image is included in the metadata; Would this require changing the way blog posts are created by users, or parsed by our indexer?

**Additional context**
This enhancement might only be worth doing if our marketing colleagues decide to use nearsocial for the near account blog.

**Comment by calebjacob** [comment]
Hey @jackson-harris-iii, let me know if you need help pairing on this or have questions - happy to help. I'll un-assign myself from this and let you take it on. 👍
