### ISSUE TITLE
near.org Data Availability Page | Logo Additions and UX Changes

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#1104]
We would like to add the following company logos to the [Data Availability page](https://near.org/data-availability) on near.org (brand assets and CTAs included in each of the links below):

Rollup Frameworks:

Optimism 
- Brand Assets (https://github.com/ethereum-optimism/brand-kit)
- CTA Link: https://docs.optimism.io/

Rollup as a Service:

Gateway 
- Brand Assets (https://gateway.fm/press-kit/)
- CTA Link: https://gateway.fm/

Ankr
- Brand Assets (https://www.ankr.com/assets/)
- CTA Link: https://www.ankr.com/

We should update the "Rollup" section to say "Blockchains" and add the following brands:

Frax Finance 
- Brand Assets (https://docs.frax.finance/other/media-kit-logos)
- CTA Link: https://frax.finance/

Particle Network
- Brand Assets (https://developers.particle.network/docs/brand-assets)
- CTA Link: https://particle.network/

**Comment by shelegdmitriy** [comment]
Just to clarify: should I add a "Optimism" to a brand new section called "Rollup Frameworks" or I can add it to the "Frameworks" section which is already exist?

cc @ravigautham @charleslavon

**Comment by ravigautham** [comment]
@shelegdmitriy Optimism should be added to the existing "Frameworks" section! Sorry for the confusion

**Comment by ravigautham** [comment]
@shelegdmitriy Can I request a small change on this issue? Could we update the CTA link for Ankr to be https://www.ankr.com/docs/scaling-services-rollups/data-availability/nearda/

**Comment by shelegdmitriy** [comment]
@ravigautham sure! Do you want to promote this change into prod today or we can wait until Tuesday?

**Comment by ravigautham** [comment]
@shelegdmitriy No rush! We can wait until Tuesday
