### ISSUE TITLE
Explore how to Mitigate UI failures due to RPC issues 

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1110]
## Problem
How might we mitigate the perceived total failure of Decentralized Frontends that occurs when there are significant issues with a gateway's RPC provider?

![image (13)](https://github.com/near/bos-web-engine/assets/1915116/90e5e684-ff20-4303-9fe7-df5216ce96df)

## Area to explore

1. Create an RoC plugin that mitigates UI failures due to RPC issues by locally storing a 24hour snapshot of recently fetched components, such that this fallback can be used when there are significant # of failures in retrieving components via RPC.  This would only mitigate the problem for returning gateway visitors. If new users land on a gateway while during RPC failures, they would not have a local component cache available for fallback.
2. A more gateway specific solution - expose a configuration that shows a list of available RPC providers, their status/uptime, and the ability to switch to a user-selected RPC provider.

**Comment by charleslavon** [comment]
relates to https://github.com/near/react-on-chain/issues/315

**Comment by calebjacob** [comment]
Hey @mpeterdev @pavelisnear, it seems like a component cache has already been implemented? https://github.com/near/react-on-chain/pull/387

How does this cache work when the RPC fetch for loading the corresponding component fails?

**Comment by mpeterdev** [comment]
Correct, we cache components after transpilation in IndexedDB and if a given component is in the cache we will not attempt to fetch it from RPC. This would only mitigate failures well if all the components are in the cache i.e. when users revisit the same dapp

**Comment by mpeterdev** [comment]
> A more gateway specific solution - expose a configuration that shows a list of available RPC providers, their status/uptime, and the ability to switch to a user-selected RPC provider.

Unfortunately this won't be possible since any component with a blockID version (which will be all embedded components by default) can only be resolved by an archival node of which we are the only provider

**Comment by charleslavon** [comment]
@mpeterdev That's great to hear. So this should be a reasonable enough mitigation of RPC failures (where there is a cache hit) such that this task can be closed for now. 

> Correct, we cache components after transpilation in IndexedDB and if a given component is in the cache we will not attempt to fetch it from RPC. This would only mitigate failures well if all the components are in the cache i.e. when users revisit the same dapp
