### ISSUE TITLE
Fix the regression in meta previews for component pages. 

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1134]
**Describe the bug**
Gateway URLs such as https://www.near.org/nearhorizon.near/widget/Index previously showed a thumbnail preview, as per [this effort](https://github.com/near/near-discovery/pull/312).  

This functionality has regressed somehow. Perhaps during the support & refactor of [social post thumbnail previews](https://github.com/near/near-discovery/blob/923e31f1e974ed0728ce17caa695ccb36224813e/src/pages/s/%5BurlShareIndicator%5D.tsx#L162).  Let's bring it back.

**Comment by shelegdmitriy** [comment]
Adding this PR https://github.com/near/near-discovery/pull/312 for the reference where this was previously implemented
