### ISSUE TITLE
`Link` is broken the router

### ISSUE THREAD

**Issue by wpdas** [near/near-discovery#1158]
**Describe the bug**
I'm facing an issue while using `Link`. It's working with all gateways except near.org. So, if I have this:

```jsx
const Link = styled("Link")``;

return (
  <Link href="?path=feature-overview">
    Go to Feature Overview
  </Link>
);
```

When I hover or click, this is going to work as expected (except for near.org):

![Screenshot 2024-05-06 at 14 23 00](https://github.com/near/near-discovery/assets/3761994/d2c6c02c-a38c-4ce7-a477-3e5d683b502a)
https://near.social/alem-lib.near/widget/Index?path=feature-overview

And this is what I'm getting when using near.org:

![Screenshot 2024-05-06 at 14 27 30](https://github.com/near/near-discovery/assets/3761994/d0e5ea60-6b7e-420b-aa8f-94b273568f39)

**To Reproduce**
1. Go to https://near.org/alem-lib.near/widget/Index
2. Click on "Learn Além"
3. See error

You can do the same using a diff gateway, and it's going to work, e.g.: https://near.social/alem-lib.near/widget/Index

**Expected behavior**
Should render the `path` correctly.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 124.0.6367.119 (Official Build) (x86_64)

**Comment by charleslavon** [comment]
hey @wpdas [Link](https://github.com/near/near-discovery/blob/d99cc2edfee83fdd9ad862c52a9a782722bd5a2b/src/components/vm/VmInitializer.tsx#L123) is a gateway-defined custom element and the near.org implementation is a bit different than that of near.social.  Are you able to add the path + the query params?

**Comment by charleslavon** [comment]
Re-opening because this seems to affect multiple apps on dev.near.org.  See [PotLock](https://dev.near.org/potlock.near/widget/Index)

**Comment by charleslavon** [comment]
hey @shelegdmitriy let's pull this into this week. What might need to change in our custom Link component to have parity with that of near.social?
