### ISSUE TITLE
Sidebar covers primary content when navigating from nearorg to dev.near.org

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1163]
**To Reproduce**
1. From https://nearorg-marketing.vercel.app/ 
2. Click on Discover -> Applications (the content layout is as expected)
3. Also try with Develop -> DevHub (the left nav overlays the primary content). 

Must this be fixed on the devhub widget side?

![nav](https://github.com/near/near-discovery/assets/1915116/967115f5-82fd-4284-84b6-ccc8aac69470)

**Comment by calebjacob** [comment]
Good catch @charleslavon. Unfortunately, this will have to be fixed on the DevHub side. They're using `position: fixed` on their root BOS component - which breaks out of the wrapping layout:

<img width="1887" alt="Screen Shot 2024-05-13 at 9 07 54 AM" src="https://github.com/near/near-discovery/assets/1475067/b1d7d9f6-8cd1-4fa4-9148-d49b72a5afcb">

They should remove `position: fixed`.

**Comment by ori-near** [comment]
Thanks for flagging @charleslavon and @calebjacob. Surfaced this to our team and will follow up with a fix / ticket for this shortly.
