### ISSUE TITLE
Offsite ideation on high-impact, low-effort focus areas

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1164]
- [ ] testing & documenting patterns that improve sign-in ergonomics, a la the hot wallet context injected into iframes
- [ ] How might we facilitate developer's in connecting their apps with the user community of existing super dapps (Sweat, HOT, KaiKai, etc). 
- [x] making RPC failure automatic via near-api-js or wallet selector -> The FailoverRpcProvider was already added into NAJ 
- [x] [Documented](https://docs.near.org/build/web3-apps/frontend) best practices for dApp development
	- large file storage
	- [onchain social DB](https://github.com/near/pagoda-experiments/issues/21)
	- decentralized UIs
	- UIs for Dapps

**Comment by andy-haynes** [comment]
> testing & documenting patterns that improve sign-in ergonomics, a la the hot wallet context injected into iframes

I documented a high level approach for this in a [Figma](https://www.figma.com/board/KDi6w6pfPPgagphxe2VNBe/dApp-embedded-Wallet-Selector?node-id=0%3A1&t=usJHcdSOH0j5gNq8-1), the gist is that the dapp is rendered in an iframe where the outer app's Wallet Selector instance gets proxied requests from the dapp's instance. This would be done entirely within Wallet Selector: on initialization the dapp's instance can detect it's operating within an iframe and establish a proxy between itself and the outer app's instance.
