### ISSUE TITLE
Add pageview event tracking for near.ai

### ISSUE THREAD

**Issue by s-n-park** [near/near-discovery#1167]
**Is your feature request related to a problem? Please describe.**
We likely want to add tracking for near.ai once that website launches to understand traffic to the website

**Describe the solution you'd like**
Add basic pageview tracking to near.ai similar to near.org and docs.near.org

**Describe alternatives you've considered**
- Alternatively, creating the AI website as a subdirectory (near.org/ai) instead of subdomain would mean we get tracking added automatically

**Additional context**
- Time permitting, adding click and touchstart events would also be useful
- We want to send to the Rudderstack destination: [Databricks Delta Lake Prod](https://app.rudderstack.com/destinations/2RWKEVTSJ3YhHbtz8HQTCI68OCV?tab=Configuration)

**Comment by s-n-park** [comment]
FYI @charleslavon - added this ticket in here without specifying sprint

**Comment by charleslavon** [comment]
The AI page has been added as [a subdirectory](https://github.com/near/nearorg/blob/11b47de5a02c12032101857467957f75121b3ecf/src/pages/ai.tsx). So we'll get analytics automatically.
