### ISSUE TITLE
Create a Wizard to get to know visitors to dev.near.org 

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1192]
Let's add into dev.near.org a wizard that asks users questions which would help us better understand our developers needs.  

[UX Designs](https://www.figma.com/design/LeXoElysTj0ckjB4vKZti5/Dev.near.org-In-Product-Continuous-Discovery-Wizard?node-id=0-1&t=4U2QMlSco7pxsGVb-0)
[Mobile UX](https://www.figma.com/design/LeXoElysTj0ckjB4vKZti5/Dev.near.org-In-Product-Continuous-Discovery-Wizard?node-id=60-1879&t=OkeDLrMXOKWvo6Jw-0)

## Additional Requirements

1. The wizard [should not appear](https://www.figma.com/design/LeXoElysTj0ckjB4vKZti5?node-id=48-932#860605361) for users who only visit `/applications`. 
2. The wizard should only appear after the Cookie Consent pop-up has been acknowledged.
3. Similar to our cookie consent pop-up, this wizard should only appear once per user session
4. One each click of 'next' we can [send the data to rudderstack with a specific event payload](https://github.com/near/near-discovery/blob/d9e9cea72a87ca13824462b468db3b38e2cbcbe8/src/utils/analytics.ts#L186) such as 
` "event": "q3_developer_survey",
    "properties": { 
        "question": 
        "answer":
         ....
     } 
`
5. @jackson-harris-iii also send an event to track the display of the wizard. So we know a total number of times the wizard was displayed so we can compare that to the number of people who actually interact with the wizard. 

Coinbase does a nice job with this. 
![coinbase](https://github.com/near/near-discovery/assets/1915116/8f7e7fed-90cf-42f9-b052-eb50ea4d2ae9)

**Comment by charleslavon** [comment]
@gagdiez check this out

**Comment by xuan-ytr** [comment]
@reiokam @vanessadespain does the customer service system we have implemented have an out-of-the-box CSAT module that can be integrated here?

**Comment by vanessadespain** [comment]
Great idea! 

I wonder if we might step back and look at the problem rather than start with a solution? Could there be lower effort both for engineering and the user to gather this type of feedback? 

Re: Docs, there are also two support/feedback mechanisms at the bottom of each doc that obscures the pagination to the next section. Might we look at a holistic effort of consolidating/improving how we're collecting feedback?

**Comment by gagdiez** [comment]
looks nice, and happy to take any approach recommended by @xuan-ytr and @vanessadespain

**Comment by reiokam** [comment]
@xuan-ytr , Unfortunately, the CSAT for Zendesk that currently exists requires a ticket to be created or submitted, before the survey can be sent. It looks like there are 3rd party apps ([ex. Formspree](https://formspree.io/blog/feedback-form/)) that exist where such a survey could be created and hooked up to Zendesk.

**Comment by charleslavon** [comment]
@vanessadespain @xuan-ytr thanks for chiming in. I've updated to remove docs.near.org from the scope here, since that UI already has a feedback mechanism.    

What information would it be helpful to gather from new developers landing on dev.near.org?

**Comment by xuan-ytr** [comment]
Possible questions to help segment the users:
* Years of experience
* Choose topics of interest - choose as many as possible
* Identity - frontend? backend? 

Qualifiers
* Professionally employed developer (more experienced)
* I have a product with users

**Comment by xuan-ytr** [comment]
First draft [here on Figma](https://www.figma.com/design/LeXoElysTj0ckjB4vKZti5/Dev.near.org-Research-Recruitment-Wizard?node-id=0-1&t=4XqfCtBrSOq59kcH-1). 

Some future-proofing questions

- Are we clear on what what make this feature successful? What metrics or qualitative outcomes are we looking to influence?
- Once our goals are crisply defined, what additional solutions, form factors, or UX are we looking at which could accomplish these goals?
- Are these the right questions to segment the audience we are interested in learning?
- What changes in requirement do we anticipate as this feature is used? How might we handle these changes over time?

**Comment by xuan-ytr** [comment]
> Might we look at a holistic effort of consolidating/improving how we're collecting feedback?

This question from @vanessadespain is also worth resurfacing. Are there any other forms of feedback or non-marketing communications we are interested in having in-product?
