### ISSUE TITLE
QueryAPI Pages point to near.org

### ISSUE THREAD

**Issue by s-n-park** [near/near-discovery#1193]
**Describe the bug**
When clicking around on QueryAPI, the website often directs to near.org instead of dev.near.org

**To Reproduce**
1. Go to https://dev.near.org/dataplatform.near/widget/QueryApi.App
2. Click on view indexer

**Expected behavior**
Directs to near.org instead of dev.near.org

**Screenshots**
<img width="1489" alt="Screenshot 2024-06-05 at 7 51 29 AM" src="https://github.com/near/near-discovery/assets/146785798/9d15b487-5ebf-4002-be56-b764796fc448">
<img width="1220" alt="Screenshot 2024-06-05 at 7 53 25 AM" src="https://github.com/near/near-discovery/assets/146785798/a8b686aa-0587-4416-bdfd-1c148e6c1877">

**Desktop (please complete the following information):**
 - OS: Macbook
 - Browser: Chrome
 - Version: 125.0.6422.142

**Comment by s-n-park** [comment]
FYI: @pkudinov - opened a bug here from what we saw on QueryAPI

**Comment by Kevin101Zhang** [comment]
issue fixed on development. Waiting on production release

**Comment by darunrs** [comment]
Resolved by https://github.com/near/queryapi/pull/768
