### ISSUE TITLE
Search improvements for dev.near.org

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1196]
**Issue 1**
The `All` category does not include results from`Apps`. 

1. search for 'inscription'
2. Notice that the NearCatalog entry for Neat - Inscription does not appear in the `All` tab. 
3. Click to the `Apps` tab to see that Neat - Inscription is included as a result

**Suggested:**  NearCatalog results should be given top priority in the display of search results in the `All` tab
![neat](https://github.com/near/near-discovery/assets/1915116/0f1eadca-ed77-48f2-860e-88a9f2649924)

**Issue 2**
1. search for 'inscription'
2. On the `Apps` tab, notice that you can get directed to a blank page if you click inbetween the  account name 'nearcatalog.near' and the app name 'NEAT - Inscription' 

**Suggested:** A valid URL should be used for all clickable links, defaulting to the leftmost selection (apps) instead of the profile
![blank](https://github.com/near/near-discovery/assets/1915116/35738772-7f70-4100-91cf-66048b2c46cb)

**Comment by shelegdmitriy** [comment]
@charleslavon is this ticket is still relevant? It seems, search is deprecated on dev.near.org so what should I do here?

**Comment by shelegdmitriy** [comment]
@gagdiez do you plan to bring search back?

**Comment by charleslavon** [comment]
hey @shelegdmitriy, let's proceed with the improvements here by adding a search icon into the left side nav menu and updating the search results to omit `People` and `Social Posts`. 

Once we get a feel for the UI with this update, we can consider how we might iterate on it further by changing the algolia index to better surface content that results in higher click through rates

**Comment by shelegdmitriy** [comment]
@gagdiez do you think this task is still relevant? If yes, I could make this change

> hey @shelegdmitriy, let's proceed with the improvements here by adding a search icon into the left side nav menu and updating the search results to omit People and Social Posts. 

otherwise let's close this task then

**Comment by charleslavon** [comment]
@shelegdmitriy yes it is relevant. [See discussion](https://pagodaplatform.slack.com/archives/C0559BC3WBZ/p1718644275606199)

**Comment by gagdiez** [comment]
@charleslavon @shelegdmitriy I think that it would be better to add a section for "Components" under Discovery, which has a search only for components, and explains that they are being deprecated

This way, people can "Discover Applications" and "Discover Components", with a fair warning of "Components will soon be removed from this page"

I understand that it drives our metrics on "search" and "click-through rate"  up... but I don't see how that is relevant to the developer experience. A global search in the Developer Portal for applications and (soon-to-be-deprecated) components might be too out of context, and thus more harming that useful.

I would expect the global search to be something more holistic, that searches on docs, tutorials, applications, etc
