### ISSUE TITLE
Near.org/ai 

### ISSUE THREAD

**Issue by LCCCunningham** [near/near-discovery#1207]
**Context**
NEAR Foundation is beginning a larger revamp of the near.org website. This process will take three to four months with an anticipated launch date in mid-late Sept 2024. In the interim period, NF needs to have a location where we can consolidate all the relevant activities, partners, and calls to action for engaging with our emerging AI ecosystem, and direct interested founders and builders to it. 

**Requirements**
Figma [design](https://www.figma.com/design/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-H1-'24-%2F-Website---v3.2024?node-id=1425-5682&t=eiJBRpGMHHpr4RJH-1) 

Specific links and assets:

Hero section CTA links:
- Work with us - https://airtable.com/appc0ZVhbKj8hMLvH/pagsVjkk5LZ66MbJm/form 
- NEAR AI R&D - near.ai 

Ecosystem Logos:
- Pond, Mizu and Nevermined logos - https://drive.google.com/drive/folders/1onZrXcFbbkR1P_suHYgXe-8EiTj-O9wP
- Pond URL - https://cryptopond.xyz/
- Mizu URL - https://mizu.global/
- Nevermined URL - https://nevermined.io/
- Hyperbolic - URL - https://hyperbolic.xyz/
- Bitte - URL - https://www.bitte.ai/
- Jutsu - URL - https://jutsu.ai/
- Nillion - URL - https://nillion.com/
- Masa - URL - https://www.masa.ai/

Get Involved:
- Are you an early stage AI Founder? --> https://www.hzn.xyz/hzn 
- Are you interested in a partnership with us? --> https://airtable.com/appc0ZVhbKj8hMLvH/pagsVjkk5LZ66MbJm/form
- Are you an AI researcher? --> near.ai
- Just want to learn more about User-Owned AI? --> https://www.youtube.com/playlist?list=PL9tzQn_TEuFWMuPiQOXhaE5lpOTnxLPZY

Events:
- Please embed the following Luma calendar - [(https://lu.ma/edgeAGI)]

**Comment by LCCCunningham** [comment]
@shelegdmitriy - updated the ticket with a link to the luma FYI

**Comment by shelegdmitriy** [comment]
@LCCCunningham is it possible to add this user devconsole-team@pagoda.co to that luma calendar? Otherwise, I can't get those events

**Comment by shelegdmitriy** [comment]
I found another way to get a list of events I think

**Comment by shelegdmitriy** [comment]
@LCCCunningham checkout this preview [link](https://vercel.live/open-feedback/nearorg-container-git-feat-create-93ade8-near-developer-console.vercel.app?via=pr-comment-visit-preview-link&passThrough=1). If this link doesn't work for you then try to open it from linked pull request.

cc @gabehamilton

**Comment by shelegdmitriy** [comment]
Hey @vanessadespain! I received this image 

![Image](https://github.com/near/near-discovery/assets/34593263/da36fb52-e35f-4fb5-8c00-b4afdf0e0bb7)

and it seems I should put it somewhere on the page but I don't understand where? The figma design still looks the same

**Comment by shelegdmitriy** [comment]
Maybe I should swap this section

![Image](https://github.com/near/near-discovery/assets/34593263/ef603dbe-933a-4686-b26a-f59aa5e0568e)

with the provided image?

cc @vanessadespain @LCCCunningham

**Comment by vanessadespain** [comment]
Hey Dmitriy,

I'm receiving your email but I don't see the comments in GitHub, perhaps
because the ticket is closed?

I'm not in the loop on this design change, but I assume you're correct that
this image you were provided is swapping for the section you highlighted.

One note of caution, I'm typically against putting a lot of text inside of
an image for accessibility reasons. This image will require a lot of Alt
text to fully describe the image/table for folks who use screen readers. In
the past I've worked with a dev who solved this by providing a table inside
of the alt text to read out the contents.

cc @LCCCunningham <https://github.com/LCCCunningham>
