### ISSUE TITLE
Near Events Page missing events

### ISSUE THREAD

**Issue by vanessadespain** [near/near-discovery#1215]
Hi @charleslavon Yadira had reached out and mentioned that not all events on their [Luma page](https://lu.ma/NEAR-community) are showing up on the near.org/events page. 

I did a little digging and found that per the [API documentation](https://docs.lu.ma/reference/calendar-list-events), an event has to be owned by the calendar that we're pulling in data from to show up. It looks like for a number of the events on their page, this Calendar/Near is a co-host but not the owner/creator of the event. 

Is there any possible work around for this? Perhaps a way to potentially pull in multiple calendars? It seems like this is a strategy of their team to create multiple calendars for different groups (like [HZN](https://lu.ma/calendar/cal-BOILOqC74o135WB)) or marquis events (like [EthCC](https://lu.ma/calendar/cal-4FqSEHPAVKh2OwH) where Near is hosting multiple events).  

I had mentioned to Yadira that the simplest workaround appears to be that all events be created by a single calendar. You could then "submit" those events to various subchannel calendars, but that could partially resolve the issue of events not showing up. Other events, like those where Near is a co-host and don't own the event, would need a different solution. I notice [Solana](https://solana.com/events) has some kind of solution for this in the Community Events section where it seems to be pulling in multiple calendars. 

Would love your thoughts! Yadira is working on getting a Github login.

**Comment by shelegdmitriy** [comment]
Well, this is really odd. But there is a solution there: if we pull the events using public api url we'll get the expected result. This is how I got the list of all the ai events. Let me prepare a PR to show you how this works. Also, using this approach we can show the community events (as far as I remember, this was in the design but we decided to skip that)
