### ISSUE TITLE
Add Gleap Help Widget on near.org and dev.near.org

### ISSUE THREAD

**Issue by reiokam** [near/near-discovery#1223]
**Is your feature request related to a problem? Please describe.**
Yes. The removal of the floating "Help/Contact Us/Support" widget from the main near.org website has resulted in a significant decrease in valuable incoming product feedback, support inquiries related to wallets, and issues with apps on the NEAR platform. This loss of direct communication channels is hindering our ability to understand user needs and improve the platform.

**Describe the solution you'd like**
To address this issue, I would like to propose re-implementing the floating help widget on the main near.org site. To expedite this process and avoid additional development work prior to the next site iteration, we can replicate the existing widget functionality from dev.near.org. This would restore a crucial communication channel for users and developers to easily contact the support team.

![Screenshot 2024-06-26 at 1 09 29 PM](https://github.com/near/near-discovery/assets/145400999/13ff7085-e7ae-4d93-a4f4-5a0b64381327)

**Describe alternatives you've considered**
The Dedicated "Contact Us" page: While a contact page exists, it requires users to navigate away from their current context, increasing friction and potentially discouraging feedback. The floating widget provides a more immediate and convenient way to reach out.

Building a new widget: Developing a new widget from scratch would introduce unnecessary delays and development effort. Reusing the existing widget is a more efficient solution until the next iteration of the site is launched.

**Additional context**
Priority: This feature request should be prioritized as it directly impacts user support, feedback collection, and overall platform improvement.

Success Metrics: After implementation, we can track the number of support requests, feedback submissions, and overall user engagement with the widget to measure its impact.

**Comment by reiokam** [comment]
Adding @ LCCCunningham for visibility from our conversation

**Comment by reiokam** [comment]
@charleslavon , would you be able to help us with this request? Discussed it with Laura offline and she was onboard with the idea.

**Comment by charleslavon** [comment]
@calebjacob please also update the link @ https://dev.near.org/contact-us to open gleap

**Comment by calebjacob** [comment]
Hey @vanessadespain, we are switching over to using Gleap for the support widget in the bottom right for `dev.near.org` and `near.org`. Gleap allows us to set a background image that displays our logo: https://app.gleap.io/projects/637cece6f1e565005237ee1e/widget

![Image](https://github.com/near/near-discovery/assets/1475067/0a4f792e-9d7d-4834-9b79-c5c9ef2e2757)

We're using an old image that says `Explorer` - but we should switch this image to something more generic that maybe says `Support`. @reiokam might have some input on the design too.

Let me know if you have questions! Thanks!

**Comment by reiokam** [comment]
Thanks for the quick @calebjacob fixes here and your input @vanessadespain . Discussed with Vanessa offline and she made all the necessary inputs and onboard with her changes!
