### ISSUE TITLE
Logo additions for Near.org/AI

### ISSUE THREAD

**Issue by vanessadespain** [near/near-discovery#1225]
Hi @shelegdmitriy! Laura requested 3 new logos be added to the AI page

Cosmose URL: https://cosmose.ai/
Exabits URL: https://www.exabits.ai/
Ringfence URL: https://www.ringfence.ai/

I dropped the logo assets in a [drive folder here](https://drive.google.com/drive/folders/15ZC8Q-XyahtIRACVKxIZRkz-Yt3MxOuq?usp=sharing)

In the design mock I added the logos in alphabetical order: 
<img width="1213" alt="image" src="https://github.com/near/near-discovery/assets/8346374/9c76f1d8-2316-4a53-b516-68126b03b177">

Please ping me or Laura if you have any questions!

**Comment by shelegdmitriy** [comment]
Thanks @vanessadespain. Seems like this new assets is in a not great quality 

![Image](https://github.com/near/near-discovery/assets/34593263/54a2a33b-2e2b-474a-bb14-f499a4ca4ae5)

**Comment by vanessadespain** [comment]
Thanks for catching this @shelegdmitriy I just re-exported them at 4x, that should match the other asset sizes. 
https://drive.google.com/drive/u/0/folders/15ZC8Q-XyahtIRACVKxIZRkz-Yt3MxOuq

**Comment by shelegdmitriy** [comment]
Thank you @vanessadespain! Is it OK to promote this changes into production today?

**Comment by vanessadespain** [comment]
Yes please
