### ISSUE TITLE
Share post links are broken

### ISSUE THREAD

**Issue by Tguntenaar** [near/near-discovery#1242]
**Describe the bug**

The short link for posts have been removed. It is hardcoded in [the Posts.Post component](https://dev.near.org/near/widget/ComponentDetailsPage?src=near/widget/Posts.Post). It seems like it used to be [https://near.org/s/p?a=account.near&b=blockHeight](https://near.org/s/p?a=webassemblymusic.community.devhub.near&b=116026696).

**To Reproduce**

See [this issue](https://github.com/NEAR-DevHub/neardevhub-bos/issues/846)

Or
1. Go to what used to be [a post link](https://near.org/s/p?a=webassemblymusic.community.devhub.near&b=116026696)
2. See 404 error

**Expected behaviour**

It should still show the page with an individual post on it or at least link to the post.

**Additional context**

It was first reported in DevHub in [this issue](https://github.com/NEAR-DevHub/neardevhub-bos/issues/846) 

Also near.social the share link button still works and will link to individual posts.

**Comment by shelegdmitriy** [comment]
Thanks @Tguntenaar for pointing this! I just want to highlight that this issue has been resolved and published into production
