### ISSUE TITLE
Build a component that allows fast auth accounts to export their account to their preferred wallet.

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1250]
Now that dev.near.org has been updated to [near-fastauth-wallet 2.0.1](https://github.com/near/fast-auth-signer/issues/249) FastAuth users can now sign arbitrary transactions, which means one could build a component that initiates a transaction to add a full access public key to a fastAuth account, and make the corresponding private key available for the user to copy and export to a wallet like [Bitte](https://wallet.bitte.ai/account/connect)

**Comment by shelegdmitriy** [comment]
Is this task is blocked by this one https://github.com/NearSocial/VM/pull/200?

**Comment by charleslavon** [comment]
@shelegdmitriy Nope. We are already using [Caleb's branch on dev.near.org](https://github.com/near/near-discovery/blob/develop/package.json#L60)
