### ISSUE TITLE
For each UX flow as an event creator, test them with each currently supported wallet

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1253]
1. Enumerate and test all the event producer flows, testing them with each of the [currently supported wallets.](https://github.com/near/pagoda-experiments/blob/fee367614959d462cc11aa05816a8339c66fb7ca/apps/ticketing/src/utils/wallet.ts#L13)  
2. Add [Bitte-wallet](https://github.com/near/wallet-selector/pull/1123) as an option & test it's flows as an event producer
3. Found turbulent UX flows or broken things? Log them as issues if non-trivial or go ahead and propose and implement solutions.

**Comment by charleslavon** [comment]
@jackson-harris-iii you can skip HERE wallet. I've found an issue there and will remove it from our options

**Comment by jackson-harris-iii** [comment]
@charleslavon I see that Bitte wallet was added to the git repo, but it is not available in the npm registry yet. That said we can manually download this package and include in the repo until the npm package is updated.
