### ISSUE TITLE
Integrate FastAuth

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1254]
1. The Sign-in buttons should launch the FastAuth Sign-in modal with our preferred wallets. See [here](https://github.com/near/near-discovery/blob/bd07f4198601adb15d8818df780a856fb6b148be/src/components/vm/VmInitializer.tsx#L97) and [here](https://github.com/near/near-discovery/blob/develop/src/hooks/useSignInRedirect.ts#L32)
3. The sign-in, manage events, and create event buttons should not appear for logged out users. e.g. when a user goes to buy a ticket)
4. Ensure all of the event producer flows work as expected as a newly created fast auth account.

**Comment by jackson-harris-iii** [comment]
Tasks 1 and 2 have been implemented by this [PR](https://github.com/near/pagoda-experiments/pull/51)

A spreadsheet documenting the testing outlined in task 3, validating the work implemented in 1 and 2 can be found [here](https://docs.google.com/spreadsheets/d/1b25a3jkBjheatymeM765Z3DjRFph4WmMt7zj_hbemQE/edit?gid=0#gid=0).
