### ISSUE TITLE
Enhancements to Ecosystem and FounderHub Pages for Improved User Experience and Navigation

### ISSUE THREAD

**Issue by jbarnes850** [near/near-discovery#1259]
**Label**
Type: Feature Request

**Request**
Enhancements to the Ecosystem and FounderHub pages on the NEAR.org website to improve user experience and navigation.

**Background**
The current Ecosystem and FounderHub pages lack clear call-to-action (CTA) buttons and contain outdated or irrelevant information, making navigation and engagement more difficult for developers, founders, and contributors.

**File to Edit**
- Ecosystem Page
- FounderHub Page

**File Location**
- [Ecosystem Page](https://github.com/near/near-discovery/blob/develop/src/pages/ecosystem.tsx) (src/pages/ecosystem.tsx)
- [FounderHub Page](https://github.com/near/near-discovery/blob/develop/src/pages/founders.tsx) (src/pages/founders.tsx)

**Changes Required**
### Ecosystem Page Changes
- **Hero Section Updates:**
  - **Headline:** Change to "Welcome to NEAR"
  - **Subheadline:** Update to "Explore a vibrant ecosystem that supports developers, founders, and contributors."
  - **CTA Buttons:**
    - Add a button linking to "Founders" (near.org/founders)
    - Add a button linking to "NEAR AI" (near.org/ai)
    - Add a button linking to "Developers" (DevHub)
    - Add a button linking to "Connect" (Onboarding and support form: https://airtable.com/appc0ZVhbKj8hMLvH/pagsVjkk5LZ66MbJm/form)

### FounderHub Page Changes
- **Hero Section Updates:**
  - **CTA Buttons:**
    - Add a button linking to “Resources” (Horizon Founder Content)
    - Add a button linking to “HZN AI incubator” (HZN.XYZ/hzn)
    - Add a button linking to "Connect" (Onboarding and support form)

- **First Subhero Section:**
  - **Title:** Change to "Welcome to NEAR, the best place to build Web3 projects: From idea to launch, the NEAR Founder Hub guides you every step of the way. Get the tailored resources, support, and community you need to launch and scale your Web3 project on NEAR."
  - **CTA Button:** Update text from “Join our community” to “Get Support” (link remains the same)

- **Self-Serve Resources Section:**
  - Remove the “Token Launch Resources” Box
  - Remove the “Founder Events” Navigation Box

- **HZN Accelerator Application Section:**
  - **Title:** Change to "HZN AI Incubator Application"
  - **Description:** Update to “Building in Web3 and AI. Apply to NEAR Horizon’s AI incubator and contribute to NEAR's User-Owned AI vision.”
  - **Link:** Update to HZN.XYZ/HZN

- **Fourth Subhero Section:**
  - Move this section to the second subhero position
  - **Title:** Change to "Join the User-Owned AI Mission"
  - **Subtitle:** Update to “Apply to NEAR's HZN AI Incubator”
  - **Description:** Update to “Put the power of AI where it belongs, in the hands of Users. Apply to be part of NEAR Foundation’s strategic vision to build a User-Owned AI ecosystem that provides alternatives to the corporate-owned, centralized AI.”
  - **CTA Button:** No change to the link or text (Apply now)

- **Fifth Subhero Section:**
  - **Title:** Change to “Get in Touch”
  - **CTA Button:** Update text to “Connect” (Link to linktree)

- **Funding Sources Section:**
  - Remove this entire subhero section, including the title, subheader, and navigation boxes:
    - “Ecosystem Grants”
    - NDC
    - She is NEAR
    - Globe DAO

**Additional context**
- [Ecosystem Page Source](https://github.com/near/near-discovery/blob/develop/src/pages/ecosystem.tsx)
- [FounderHub Page Source](https://github.com/near/near-discovery/blob/develop/src/pages/founders.tsx)

### Reference Images:

- **FounderHub Hero Section Update:**
<img width="912" alt="Screenshot 2024-07-19 at 10 27 33 AM" src="https://github.com/user-attachments/assets/644da8ff-5ce4-4f32-9c3e-22c1c06ffc51">

- **Funding Sources Removal:**
<img width="566" alt="Screenshot 2024-07-19 at 10 24 17 AM" src="https://github.com/user-attachments/assets/2000d21a-9400-4e1c-80cf-80040f4bcf03">

- **FounderHub Updates:**
<img width="623" alt="Screenshot 2024-07-19 at 10 23 55 AM" src="https://github.com/user-attachments/assets/ce81e91c-f2b2-4438-a1f8-5d17000b1980">

**Comment by calebjacob** [comment]
Hey @jbarnes850, what's the Linktree URL for this change?

> Fifth Subhero Section:
Title: Change to “Get in Touch”
CTA Button: Update text to “Connect” (Link to linktree)

**Comment by calebjacob** [comment]
@jbarnes850 Do you have a new design asset to replace the image marked in red?

![Image](https://github.com/user-attachments/assets/13067ec8-355b-4a41-a7a9-83ea61514cfa)

Also, what should happen to the existing description?

```
Horizon is an early stage accelerator for Web3 founders to build, connect, and grow.
```

**Comment by jbarnes850** [comment]
@calebjacob - thanks so much for jumping on this! 

- Here is the link to the linktree for the "Connect" CTA: https://linktr.ee/joinNEARcommunity

- We're in the process of redesigning the NEAR Horizon Website (this recommendation was made prematurely). We can keep the existing image for now. 

Let me know if there's any other info/context I can share!

**Comment by calebjacob** [comment]
Thanks for the info! That should be all I need. I'll let you know when the changes are ready to preview.

**Comment by calebjacob** [comment]
@jbarnes850 the changes are live on https://near.org/ - let me know if we need any further changes.
