### ISSUE TITLE
Improve the UX of the TransferNear and WalletExport MVPs

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1265]
1. This [TransferNear component ](https://dev.near.org/7aky18df3-test.near/widget/TransferNEAR)was created to give FastAuth accounts the ability to transfer funds away from their account.  At a minimum, we should improve this UI, inspired by [these designs](https://www.figma.com/design/MAwjXYI4b7VesfEO2QzUQ3/Account-Management?node-id=345-48336&t=UIGYbcf6Fij9z0KE-0) and perhaps expand the functionality to allow one to send
 any FT. Please collab with @nall-near @gagdiez  and @xuan-ytr to discuss and mitigate UX and security concerns.  
2. Introduced in [this draft-PR](https://github.com/near/near-discovery/pull/1256) this [/addKey](https://dev-near-org-git-fakexport-near-developer-console.vercel.app/addKey) UI allows FastAuth accounts a path to create a new full access key and instruct them on how to import their account to a standard wallet.   We should improve this UI, perhaps in a style matching the designs above, and also add instructions to guide the user to import their account to several wallets; e.g. Bitte Wallet, Meteor Wallet, HERE Wallet, and My Near Wallet.
3. Be sure to do an extensive review here and get feedback from Eric before merging the above into production.

Where should these UIs live? Perhaps we re-purpose the 'Profile -> Withdraw' affordance to launch a UI that shows these wallet like components

**Comment by calebjacob** [comment]
My plan is to knock this ticket out first to give us access to our component library: https://github.com/near/pagoda-experiments/issues/64

This will allow us to build out the suggested Figma designs as a native Next JS / React page within `near-discovery`.
