### ISSUE TITLE
How might we track usage and errors related to chain-deployed-uis?

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1267]
The MVP currently uses [this contract](https://testnet.nearblocks.io/address/pfs1.testnet) on testnet. How should we capture and visualize data to be able to report on usage trends and errors for this novel approach to hosting decentralized UIs on near. 

+ @mpeterdev @s-n-park penny for your thoughts.

**Comment by s-n-park** [comment]
@mpeterdev , @charleslavon - thanks to Eduardo who built out testnet pipeline in Databricks, we can parse this data relatively easily.

Here's splitting out number of receipts by method name which interestingly shows delete_file and upload_file_partition as the 2 most common.
![image](https://github.com/user-attachments/assets/01751a43-a1f5-423d-8e7c-0fb6fedda0df)

[Query](https://4221960800361869.9.gcp.databricks.com/sql/editor/e028f0fc-0a2a-4433-846b-1358a539c0d6?o=4221960800361869)

I can also break down into the specific args like filename, totalparts, etc.
