### ISSUE TITLE
Label checker action is failing

### ISSUE THREAD

**Issue by calebjacob** [near/near-discovery#1275]
Hey @charleslavon, I've noticed that our `Label Checker / Check labels (pull_request)` job is consistently failing on PR's:

<img width="1563" alt="Screenshot 2024-08-02 at 7 35 50 AM" src="https://github.com/user-attachments/assets/5953cfe1-9888-4636-a0cc-34df899a73dd">

Example: https://github.com/near/near-discovery/actions/runs/10216538255/job/28268227559?pr=1273

**Comment by charleslavon** [comment]
This appears to have self-resolved.
