### ISSUE TITLE
Fix formatting on wallet utilities

### ISSUE THREAD

**Issue by flmel** [near/near-discovery#1343]
**Describe the bug**
Fix the formatting on wallet utilities page

**To Reproduce**

Go to https://dev.near.org/wallet-utilities

**Expected behavior**
Human friendly formatting

**Screenshots**
<img width="492" alt="Screenshot 2024-11-11 at 20 47 27" src="https://github.com/user-attachments/assets/5e1889cc-3fb3-4010-8a04-996fabb2056f">

**Comment by Pawar7349** [comment]
Hi! I'd like to work on this issue. Please assign it to me.

**Comment by flmel** [comment]
Hey @Pawar7349 thanks for taking that up!
