### ISSUE TITLE
Login Page Displays After Logging In

### ISSUE THREAD

**Issue by doriancrutcher** [near/near-discovery#183]
I've notice that after signing in with my NEAR Wallet this sign in page continues to display. 

<img width="821" alt="image" src="https://user-images.githubusercontent.com/59028579/236032260-b1c1dca3-76af-44a6-a71b-8f16c4340aa5.png">

**Comment by parthibanb224** [comment]
what is the issue?

**Comment by charleslavon** [comment]
This is [been resolved](https://github.com/near/near-discovery/pull/278)
