### ISSUE TITLE
VM is dead on full refresh w/ bos-loader (beta.near.org)

### ISSUE THREAD

**Issue by petarvujovic98** [near/near-discovery#238]
When using the [bos-loader](https://github.com/near/bos-loader), on a full page reload I get some _VM is dead_ errors for certain components for a brief moment. The first time I launched it (before being logged in, but after setting the flags for the bos-loader) all components showed this behavior.

https://github.com/near/near-discovery/assets/36507050/c3e372c0-6b0e-432a-98db-066fb5db6dd5

**Comment by charleslavon** [comment]
This occurs on beta.near.org
