### ISSUE TITLE
Unable to fork `ProfileEditor` widget

### ISSUE THREAD

**Issue by shelegdmitriy** [near/near-discovery#29]
For some reason I can't fork [ProfileEditor](https://alpha.near.org/#/calebjacob.near/widget/ComponentDetailsPage?src=mob.near/widget/ProfileEditor) widget.

Maybe this bug relates not to only this widget.

Here is loom video: https://www.loom.com/share/db14f28b226d4a54801f6f3b2ae36e9d
More context here: https://pagodaplatform.slack.com/archives/C04QKBVV7DF/p1678808887723779

**Comment by mpeterdev** [comment]
@shelegdmitriy please check if this is still an issue and close if not
