### ISSUE TITLE
General Performance Issues

### ISSUE THREAD

**Issue by calebjacob** [near/near-discovery#313]
The performance of more complex pages like the [Activity Page](https://near.org/near/widget/ActivityPage) can be fairly poor (slow load time, interaction lag) depending on your connection quality and device. When running the gateway locally, the performance issues are far worse - even on high end connections and modern devices.

Is this an issue with the VM? Or with how we're initializing and utilizing the VM within our Next JS application? It's a tough question, but worth digging into.

**Comment by mpeterdev** [comment]
worth looking into the number of web requests being made on load, I believe Marcin called out that they were abnormally high

**Comment by charleslavon** [comment]
Performance has been greatly improved for the Activity Page since last week's merge of the QuerAPI powered feed into near.org.   @calebjacob What are the other problematic pages/components that we should use this issue to track? A probably pattern we'll want to apply is to re-write components to leverage QueryAPI.

**Comment by calebjacob** [comment]
@charleslavon You're right, the activity page in production is much improved after the Query API changes. When running the server locally with `pnpm dev`, the activity page still really struggles to load - the page is unresponsive for a few seconds. It appears to be an issue with loading the components more so than the post data.

In general, we should probably start adopting the Query API in more places. It would also be helpful to investigate why `pnpm dev` performs so much worse than a production build.
