### ISSUE TITLE
Make the NearCon banner smarter - so it remembers when one chose to hide it 

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#349]
The NearCon banner currently has an X icon that hides the banner upon click, but this choice the hide the banner isn't saved, thus the banner reappears whenever a new near.org tab is opened. 

<img width="1190" alt="Screen Shot 2023-08-29 at 11 48 58 AM" src="https://github.com/near/near-discovery/assets/1915116/c7779b4b-0f53-47d5-96a3-814f81bdb74e">

**Ideal UX**
Update the banner such that it saves some state in the client and does not re-appear after someone has chosen to hide it.

**Comment by shelegdmitriy** [comment]
Basically we save state of banner in sessionStorage as it was described in task. But we can change it to localStorage to solve this
