### ISSUE TITLE
Improve the hover & click behavior of the near.org navigation menu

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#363]
**Problem**
We're received some feedback mentioning being annoyed by having to chase menu options and unexpected UX of click vs hover.   @heycorwin this might be worth considering with the new nav designs.   We could leverage an approach mentioned in this analysis of an [Amazon menu](https://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown?utm_source=pocket_reader)

**Comment by thisisjoshford** [comment]
+1 on this being a common area of feedback that I receive from people. (hover & click seems wonky)

**Comment by charleslavon** [comment]
yea I'm not able to reproduce this as much as I was before.
