### ISSUE TITLE
Here Wallet should not be an option from a Desktop client

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#367]
**Problem**
The Here wallet exists as a downloadable mobile app. Here does not currently have a web client wallet. Therefore, when near.org offers desktop users the option to connect via here wallet, users are unable to complete this flow because a web login option does not exists for Here wallet users. 

**To Reproduce**
1. Go to near.org from a desktop browser
2. Click on Sign In -> Continue with Wallet
3. Choose Here
4. Try to complete the sign in flow

**Expected behavior**
We should only offer Here wallet as an option in wallet selector if users are on a mobile device

**Comment by mpeterdev** [comment]
@charleslavon 
HERE wallet can be used on desktop, it is actually my wallet of choice for that. The wallet selector should present a QR code which can be scanned by the mobile app in order to complete sign in on the web

**Comment by calebjacob** [comment]
@mpeterdev Good point - it does show a QR code and links to download the app.

**Comment by mpeterdev** [comment]
![Screenshot 2023-09-27 at 1 07 27 PM](https://github.com/near/near-discovery/assets/24904709/8bbb394d-d1d1-488f-8a33-0d4fb9084de3)

**Comment by mpeterdev** [comment]
ah it looks like we need to bump wallet selector. `signMessage` support for HERE was added in `8.5.2` and we are on `8.5.1`

https://github.com/near/wallet-selector/releases/tag/v8.5.2

**Comment by charleslavon** [comment]
Thanks @mpeterdev  

@calebjacob we can close this ticket. Apologies for the misdirection
