### ISSUE TITLE
Add short URL for Profile Page

### ISSUE THREAD

**Issue by sainthiago** [near/near-discovery#37]
Is there a way to add a short url for the public profile widget?

https://alpha.near.org/#/sainthiago.near would redirect to https://alpha.near.org/#/adminalpha.near/widget/ProfilePage?accountId=sainthiago.near

**Comment by thisisjoshford** [comment]
ooh, that would be cool! and now that alpha -> near.org it could be near.org/santhiago.near.

**Comment by charleslavon** [comment]
A few changes have been made - the URL has been shorted to `https://near.org/near/widget/ProfilePage?accountId=sainthiago.near`
