### ISSUE TITLE
P0 [NEARCON] Give ability for moderators to hide objects

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#407]
Description

Allow a moderator to prevent an individual post from appearing on the primary socialdB feed. 

User Experience

While reviewing content in our queue https://near.social/#/mob.near/widget/Flagged.Feed  moderators will have access to a button on the right side of the post/comment which, upon clicking on it, will give them the ability to hide the post/comment from the primary socialdB feed.

Design

The screenshot below is an example
<img width="1345" alt="Screenshot 2023-08-10 at 14 54 47" src="https://github.com/near/near-discovery/assets/5955639/ceba452d-634b-4707-91e9-b56f6b4cbb3d">

```[tasklist]
### Tasks
- [x] New design for Moderators to work in FlaggedFeed
- [x] Use DIG Components in Moderator interface
```

**Comment by xuan-ytr** [comment]
Notes from co-working session with @gabehamilton 
Improvements upon moderation queue:
- How does a moderator act on post
- Bulk processing
- un-moderate

@tidus974 should moderators be able to filter the moderation queue by the reasons that the reporter submitted? I.e. filter by nudity or terrorism content?

**Comment by tidus974** [comment]
At this stage I don't think it's necessary because of the low volume. But in the future we might organize queues as such or also by languages yes
