### ISSUE TITLE
near.org Home

### ISSUE THREAD

**Issue by heycorwin** [near/near-discovery#411]
**Design Status update:** 
- Layout is largely defined at this point. 
- Assets are being created and gathered. 

**To do:** 
- Finalize design to support copy
- asset creation
- design specs for all modules. 

**Files:** 
- [Working File](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-68289&mode=design)
- [Dev Ready Design Specs](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-5545&mode=design)

**Dev ready elements:** 
- Grid and Breakpoint logic
- Large image with description module

**Homepage design:**
![Home](https://github.com/near/near-discovery/assets/8346374/2ae4f013-8b88-4408-a4b2-5ffc51eaf397)

**Comment by vanessadespain** [comment]
**Design Status update:** Layout is largely defined at this point. Assets are being created and gathered. 

**To do:** Finalize design to support copy, asset creation, dev specs for all modules. 

**Files:** 

- [Working File](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-68289&mode=design)
- [Dev Ready Design Specs](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-5545&mode=design)

**Dev ready elements:** Grid and Breakpoint logic and Large image with description module

**Homepage design:**
![Home](https://github.com/near/near-discovery/assets/8346374/2ae4f013-8b88-4408-a4b2-5ffc51eaf397)
