### ISSUE TITLE
near.org Learn

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#412]
**Design Status update:** 
- Layout is largely defined at this point. 
- Assets are being created and gathered. 

**To do:** 
- Finalize design to support copy
- asset creation
- design specs for all modules. 

**Files:** 
- [Working File](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=964%3A22334&mode=design&t=DdDZMoOXS6mOWKjy-1)
- [Dev Ready Design Specs](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-5545&mode=design)

**Dev ready elements:** 
- Grid and Breakpoint logic
- Large image with description module

**Learn page design:**
![Learn](https://github.com/near/near-discovery/assets/8346374/9f3e5707-9288-4c03-8d5e-6aaf493371d0)

**Comment by vanessadespain** [comment]
**Design Status update:** 
- Layout is largely defined at this point. 
- Assets are being created and gathered. 

**To do:** 
- Finalize design to support copy
- asset creation
- design specs for all modules. 

**Files:** 
- [Working File]https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=964%3A22334&mode=design&t=DdDZMoOXS6mOWKjy-1
- [Dev Ready Design Specs](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-5545&mode=design)

**Dev ready elements:** 
- Grid and Breakpoint logic
- Large image with description module

**Ecosystem page design:**
![Uploading Learn.png…]()
