### ISSUE TITLE
near.org Ecosystem

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#413]
**Design Status update:** 
- Layout is largely defined at this point. 
- Assets are being created and gathered. 

**To do:** 
- Finalize design to support copy
- asset creation
- design specs for all modules. 

**Files:** 
- [Working File](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=964%3A21980&mode=design&t=DdDZMoOXS6mOWKjy-1)
- [Dev Ready Design Specs](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-5545&mode=design)

**Dev ready elements:** 
- Grid and Breakpoint logic
- Large image with description module

**Ecosystem page design:**
![Ecosystem](https://github.com/near/near-discovery/assets/8346374/c5ca06d6-fc6d-4ce2-a4ba-541e0ff943df)

**Comment by vanessadespain** [comment]
**Design Status update:** 
- Layout is largely defined at this point. 
- Assets are being created and gathered. 

**To do:** 
- Finalize design to support copy
- asset creation
- design specs for all modules. 

**Files:** 
- [Working File][(https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-68289&mode=design)](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=964%3A21980&mode=design&t=DdDZMoOXS6mOWKjy-1)
- [Dev Ready Design Specs](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-5545&mode=design)

**Dev ready elements:** 
- Grid and Breakpoint logic
- Large image with description module

**Ecosystem page design:**
![Ecosystem](https://github.com/near/near-discovery/assets/8346374/c5ca06d6-fc6d-4ce2-a4ba-541e0ff943df)
