### ISSUE TITLE
near.org Events

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#414]
**Design Status update:** 
- Layout is largely defined at this point. 
- Assets are being created and gathered. 

**To do:** 
- Finalize design to support copy
- asset creation
- design specs for all modules. 

**Files:** 
- [Working File](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=968%3A24962&mode=design&t=DdDZMoOXS6mOWKjy-1)
- [Dev Ready Design Specs](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-5545&mode=design)

**Dev ready elements:** 
- Grid and Breakpoint logic
- Large image with description module

**Events page design:**
![Events](https://github.com/near/near-discovery/assets/8346374/c03d5dd9-e3ec-42ee-a110-757402ae8f7e)

**Comment by vanessadespain** [comment]
**Design Status update:** 
- Layout is largely defined at this point. 
- Assets are being created and gathered. 

**To do:** 
- Finalize design to support copy
- asset creation
- design specs for all modules. 

**Files:** 
- [Working File](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=968%3A24962&mode=design&t=DdDZMoOXS6mOWKjy-1)
- [Dev Ready Design Specs](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-5545&mode=design)

**Dev ready elements:** 
- Grid and Breakpoint logic
- Large image with description module

**Events page design:**
![Events](https://github.com/near/near-discovery/assets/8346374/c03d5dd9-e3ec-42ee-a110-757402ae8f7e)

**Comment by charleslavon** [comment]
@shelegdmitriy Vanessa has new/simplified designs in progress to be shared soon.   Let's sync on how we'll integrate with https://lu.ma/ChADay

**Comment by vanessadespain** [comment]
Here is my nearly done link to the latest designs: [Figma link](https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=537%3A28934&mode=design&t=TMQz293fqitIfvhe-1)

Today I'll wrap up one remaining layout/responsive design to finish up and provide developer annotations for how interactions should look and perform.

**Comment by vanessadespain** [comment]
Updated designs are in Figma now! Please ping me if there are any open questions. 

I did some work today on getting the Events team's Luma page more setup to allow community to submit their events. 
The public facing page that will allow events to be submitted for approval is: https://lu.ma/NEAR-community

@charleslavon I also helped get the Luma account setup to allow multiple admins which will allow us to give a developer login. What email should be used for this? There are a limited number of seats in the account, so perhaps an alias that goes to the relevant folks?

**Comment by shelegdmitriy** [comment]
Thanks @vanessadespain! The design looks great! I just left a couple of comments there
