### ISSUE TITLE
near.org Blog

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#415]
**Design Status update:** 
- Layout is largely defined at this point. 
- Assets are being created and gathered. 

**To do:** 
- Finalize design to support copy
- asset creation
- design specs for all modules. 

**Files:** 
- [Working File](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=572%3A99614&mode=design&t=DdDZMoOXS6mOWKjy-1)
- [Dev Ready Design Specs](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-5545&mode=design)

**Dev ready elements:** 
- Grid and Breakpoint logic
- Large image with description module

**Blog page design:**
![Blog](https://github.com/near/near-discovery/assets/8346374/9137bc8d-db87-4f0b-8618-8d7ff7a035aa)

**Comment by vanessadespain** [comment]
**Design Status update:** 
- Layout is largely defined at this point. 
- Assets are being created and gathered. 

**To do:** 
- Finalize design to support copy
- asset creation
- design specs for all modules. 

**Files:** 
- [Working File](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=572%3A99614&mode=design&t=DdDZMoOXS6mOWKjy-1)
- [Dev Ready Design Specs](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=562-5545&mode=design)

**Dev ready elements:** 
- Grid and Breakpoint logic
- Large image with description module

**Blog page design:**
![Blog](https://github.com/near/near-discovery/assets/8346374/ca0929fd-a7fb-4958-ace4-cc0a4a43b5d9)
