### ISSUE TITLE
P4 [NEARCON] Give ability for users to block another account

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#422]
Disclaimer! This might fall into the Customized Content Filtering Work and need to be discussed as a team to understand whether they should be developed together. cc @gabehamilton just as a FYI

Describe

Give users the ability to block any account anywhere on [near.org](http://near.org/) (e.g. on the feed, account profile etc…)

Details

"Blocking" is a tool that allow users to control their interactions and what content they see. 

Purpose: To prevent specific users from interacting with you or seeing your content.

Effects:

  i. The blocked user typically cannot view your profile or posts.

  ii. You and the blocked user won't see each other's comments or posts on mutual friends' or public pages.

  iii. The blocked user is usually unaware they've been blocked unless they try to visit your profile or interact with you.

  iv. Blocking often unfollows or removes the blocked user from your followers list and vice versa.

   

Figma/Design
[
Add icons next to “Flag a user“ icon and give ability for users to chose between block and hide (potentially give a quick explanation of what these options would do)](https://www.figma.com/proto/bD7wRz3SLLh0N2EwTFjFEQ/Reporting?page-id=1%3A2&type=design&node-id=114-1535&viewport=-1012%2C773%2C0.5&t=0EcdkXv3YM8HPmYu-1&scaling=scale-down-width&starting-point-node-id=114%3A1535)

![Image](https://github.com/near/near-discovery/assets/5955639/22ec3b29-80a2-496c-88db-df01130811a3)
![Image](https://github.com/near/near-discovery/assets/5955639/19d7bae3-98c8-41da-96c1-d4648f16053e)

**Comment by gabehamilton** [comment]
Can we separate Block and Hide into different issues? Hide is being implemented [here](https://github.com/near/near-discovery-components/issues/320) and [here](https://github.com/near/near-discovery-components/issues/315)  .
Block can use the same functionality from the perspective of the blocking user, implementing the other side (blocked user can't see blocking user's content) will be complex.

**Comment by tidus974** [comment]
@gabehamilton absolutely. I will amend this task to focus only on block action. Hope that helps
