### ISSUE TITLE
Notifications - historical data endpoint

### ISSUE THREAD

**Issue by milenakrawczyk** [near/near-discovery#509]
Notifications-server should expose a historical data endpoint to show the following:
* number of notifications sent in the last X days
* number of active subscriptions
* number of active users

**Comment by milenakrawczyk** [comment]
@charleslavon what other statistical data should be available for those endpoints? I assume we also need an authentication for this endpoint? What would be the client that would fetch this data?

**Comment by charleslavon** [comment]
@milenakrawczyk add here to record what we discussed previously - directly access our postgresDB with [defined queries](https://docs.google.com/spreadsheets/d/194GrC7_tcMffLrykupBrEFyPHHneb5jQJcim07lHO00/edit#gid=0) is good enough for now. 

Marking this task as closed.
