### ISSUE TITLE
Notifications - notifications threshold per day

### ISSUE THREAD

**Issue by milenakrawczyk** [near/near-discovery#511]
For now, the notification-serverless-function will send all notifications for a given receiver. The amount of the notifications send in the last 24 hours should be curbed to a specific number.

The check for the number of already sent notifications should be performed before a notification is sent to the user. The number of  messages per day should be set as an environment variable.

**Comment by charleslavon** [comment]
I believe this has been completed. @milenakrawczyk please re-open if I'm mistaken
