### ISSUE TITLE
P0 [NEARCON] Update Privacy Policy

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#526]
Update the content @ near.org/privacy to reflect the [latest privacy policy](https://docs.google.com/document/d/1LlPCs9WZym2N_mdlgNxlspf9qNh-7Y3V/edit#heading=h.gjdgxs)

**Comment by shelegdmitriy** [comment]
[near.org/privacy](https://near.org/privacy) are showing a content from https://pages.near.org/privacy using `IframeResizer` component which means I can't really make changes there.

cc @charleslavon

**Comment by charleslavon** [comment]
@shelegdmitriy yes, that's right. The intended change is to add a new route into our repo and format content from the linked google doc. So we will no longer need to reference the iframed privacy like we currently do.

**Comment by shelegdmitriy** [comment]
At this moment we do have a new infura account and the new file with privacy policy are already there too
