### ISSUE TITLE
🔷 [Epic] MVP Notification Developer Documentation and Guidelines

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#542]
- Set of developer guidelines, documentation, and tutorials that will help BOS developers implement notifications for applications

**Comment by ravigautham** [comment]
@gagdiez can we close this epic?

**Comment by gagdiez** [comment]
Documentation can be found here:

- https://docs.near.org/bos/api/notifications
- https://docs.near.org/bos/tutorial/push-notifications
