### ISSUE TITLE
Notification standards

### ISSUE THREAD

**Issue by milenakrawczyk** [near/near-discovery#547]
There is a PR on notification standards that has been stale for quite some time: https://github.com/NearSocial/standards/pull/19.
The notification standards are an important part of documentation for developers. This task consists in fixing the PR and merge it into NearSocial.

**Comment by thisisjoshford** [comment]
Thanks for flagging this @milenakrawczyk ! I came across it going through the standards repo in NearSocial. 

@Ishatt can you assist with making sure we don't lose track of this issue? Zooming out, and working with the NearSocial Standards repo will be super important as we start to standardize primitives like this and component forks.
