### ISSUE TITLE
Notifications from dApps like DevHub have incorrect UI treatment in Notification Tab

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#582]
In the notification tab, push notifications from all apps should be featured the same way with the same UI treatment. In the image below, notifications from DevHub are appearing differently. We need to have a consistent UI treatment. 

![image](https://github.com/near/near-discovery/assets/129213007/dc1146d6-c603-4489-ac25-f457842dc727)

**Comment by charleslavon** [comment]
duplicates https://github.com/near/near-discovery/issues/627
