### ISSUE TITLE
Notification Tab should appear when user hovers over notification icon

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#585]
As shown below, figma file also linked.

<img width="539" alt="image" src="https://github.com/near/near-discovery/assets/129213007/74532044-d478-441c-b070-c78c8984e621">

https://www.figma.com/file/Cm6qATC1CpK9nUrKgx5K3U/Notifications?type=design&node-id=2-19009&mode=design&t=FoqNBN1DKwPlwzVi-4

**Comment by marcinbodnar** [comment]
It's already done
