### ISSUE TITLE
Push-notifications-server - websocket closes after a few minutes

### ISSUE THREAD

**Issue by milenakrawczyk** [near/near-discovery#599]
The websocket connection to Hasura is closed after a few minutes with 1006 code and no reason message. Pinging the server has been implemented to keep the connection alive but the issue still persists.

**Comment by charleslavon** [comment]
@milenakrawczyk  Of the remaining tasks that we have proposed to improve the UX of push notifications, is this task likely the most impactful and least complex?

**Comment by milenakrawczyk** [comment]
I implemented a workaround so the socket keeps reconnecting whenever the connection is lost. For now, I would classify this task as the least impactful and the most complex. I tried to fix it but the issue keeps persisting. This task would become more impactful when the number of notifications increases significantly because the reconnection time could cause delays.

**Comment by milenakrawczyk** [comment]
[This task](https://github.com/near/near-discovery/issues/573) may actually solve the issue since my assumption for now is that the closing websocket issue might be Node-specific.
