### ISSUE TITLE
[Push Notifications] Do not work on mobile iOS chrome/safari

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#600]
**Describe the bug**
Our Enable Push Notifications modal is unresponsive upon clicking 'Turn On'. The same happens when trying to enable push notifications from the Notifications alert dropdown.

Do we get any indication of error here? If so we should use it to prompt the user to follow the iOS required steps of saving the icon to the home screen. @marcinbodnar I've created a separate issue for [this missing Add to Home Screen modal](https://github.com/near/near-discovery/issues/604). 

![mobile](https://github.com/near/near-discovery/assets/1915116/6fee16e4-eac7-42fe-9821-053464481d4d)

****
1. On mobile Safari or Chrome, log into beta.near.org
2. Wait for the modal to appear or click on the Notifications alert icon
3. Click Turn On
4. Nothing Happens

**Expected behavior**
Clicking Turn On should prompt the browser to request that user to enable Web Push

**Comment by marcinbodnar** [comment]
Closing #615
