### ISSUE TITLE
[Push Notifications] Mobile iOS Set Home Icon screen is missing 

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#604]
**Describe the bug**
For iOS devices only, we want to show this [Add to Home Screen UI](https://www.figma.com/file/Cm6qATC1CpK9nUrKgx5K3U/Notifications?type=design&node-id=94-1480&mode=design&t=3vz4RENcLToKuHMw-0) This is a modal which should appear before the Enable Push Notifications Modal.

**Comment by shelegdmitriy** [comment]
@charleslavon What is this task about? I just need to add an icon? Is this related to this [PR](https://github.com/near/near-discovery/pull/615)?
