### ISSUE TITLE
🔷 [Epic] Developer Home/Dashboard Screen

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#616]
## Description
(Overview of milestone or function governed by this epic)

## Resources
(Relevant documentation, Figma links, and other reference material)

1. Item 1
1. Item 2
1. Item 3

**Comment by charleslavon** [comment]
@ravigautham what's the scope of this initiative? Does this intent to track the home, learn, use, and ecosystem pages?

**Comment by ravigautham** [comment]
@charleslavon 

This overall initiative is for the new global navigation for the near.org gateway (logged in) experience that Corwin is building in his prototype. The Developer Dashboard/Home screen would be a net new screen that we'd need to build as a result of that new navigation. So I've called it out as a separate epic here.
