### ISSUE TITLE
Notifications - profile data is appearing incorrectly for "like" notifications in the notifications tab

### ISSUE THREAD

**Issue by milenakrawczyk** [near/near-discovery#637]
Clicking a link on a 'like' notification in the notifications tab routes to an incorrect profile.

**Comment by ravigautham** [comment]
<img width="807" alt="Screenshot 2023-09-29 at 10 30 51 AM" src="https://github.com/near/near-discovery/assets/129213007/659fbf42-c328-4c88-a0bf-e643177173d5">
