### ISSUE TITLE
Implement alert

### ISSUE THREAD

**Issue by shelegdmitriy** [near/near-discovery#647]
Design item https://www.figma.com/file/dmfi3WIjvfyoXBVaPdqRvt/IDOS?type=design&node-id=356-18910&mode=design&t=v5EX61IIOfApYWOt-4

**Comment by shelegdmitriy** [comment]
Do we really need to implement a new type on alert? I mean we are already have this [tooltip](https://www.figma.com/file/hbEv4eGUqzov3spuVgn5ig/Components?node-id=781%3A1475&mode=dev) (DIG.Tooltip) so I wonder we can use DIG.Tooltip instead of new alert?

cc @charleslavon

**Comment by charleslavon** [comment]
@xuan-ytr @heycorwin what say ye on Dima's question above?

**Comment by heycorwin** [comment]
I don't think @xuan-ytr was aware of the recent addition of that component, which makes a good case for us to do a better job of broadcasting new component library additions to our design team :) Good call! These two components do function similarly, so unless @xuan-ytr objects, I think it's fine to go ahead with the existing component you referenced @shelegdmitriy.

That being said, the name `Tooltip` is actually used for a [different component](https://www.figma.com/file/hbEv4eGUqzov3spuVgn5ig/Components?type=design&node-id=1749-9&mode=dev) than this one. This one should be called a `Toast`.

**Comment by xuan-ytr** [comment]
100% agree. @shelegdmitriy 
- Feature design specs are meant to illustrate functionality
- please substitute DIG components as they become available

**Comment by shelegdmitriy** [comment]
@heycorwin yes, you're right! I meant DIG.Toast 😀

**Comment by shelegdmitriy** [comment]
> 100% agree with @heycorwin . @shelegdmitriy this is how I like to think about the "specs" I hand off:
> 
> * Feature design specs are meant to illustrate functionality
> * please substitute DIG components as they become available
> 
> Does this work for you? I'd be happy to sync up with you on how you like handoffs going forward.

Sure it's fine!

**Comment by xuan-ytr** [comment]
Thank you @shelegdmitriy for making sure with us! I'm really impressed by our team's attention to frontend details. Always a sign of healthy eng<-->design collaboration!

**Comment by shelegdmitriy** [comment]
I'm going to close this task and create another one to close this epic and do not lose it
