### ISSUE TITLE
Notification Icon does not show the count of unread notifications

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#655]
**Describe the bug**
The alert icon should show a count of unread alerts, but it does not. 

<img width="838" alt="Screen Shot 2023-10-03 at 4 58 27 PM" src="https://github.com/near/near-discovery/assets/1915116/87479a9e-23e4-4dee-8af2-afd3a692a939">

**To Reproduce**
1. log into https://near-discovery-alpha.vercel.app
2. trigger an alert to your account
3. The notification bell icon should show a count of unread alerts

**Comment by shelegdmitriy** [comment]
I can reproduce it using provided link + prod but can't do the same locally 😞
