### ISSUE TITLE
🔷 [Epic] Dev Onboarding v0.1.0

### ISSUE THREAD

**Issue by thisisjoshford** [near/near-discovery#657]
### Description

The first iteration in enhancing developer onboarding for near.org & BOS development. In this phase we will update the online IDE layout that will be required for subsequent versions of dev onboarding. Once the layout is complete we will resolve issues with the existing onboarding flow by replacing it with a temporary walkthrough via video or carousel slides. 

Additionally, we should ensure that developers are able to easily find resources they need on near.org and understand the basic functionality of near.org & the IDE.  

---

### Goal

- Developers new to near.org understand how to use it and where to find resources they need. 
- A new foundation is created that future onboarding iterations will be built on 

---

### Resources

- [IDE Design](https://www.figma.com/file/wiHosmPTJOf2pUeplEnh0b/Developer-Onboarding-MVP?type=design&node-id=28-5671&mode=design&t=Wf29lFi8F4VyHUFH-0) 

---

```[tasklist]
### Related Issues
- [ ] https://github.com/near/near-discovery/issues/689
- [ ] https://github.com/near/near-discovery/issues/765
```

**Comment by charleslavon** [comment]
@heycorwin @thisisjoshford I think we should separate the `Interactive Documentation` effort away from the effort to `Rebuild the IDE`. My hypothesis is that the former is a more effective way to improve the onboarding experience, and the IDE rebuild is something that we should not do - Rather we should ideate on another way to bridge near.org to a smooth development experience.

**Comment by thisisjoshford** [comment]
So adding interactive documentation into the existing IDE is your proposal, correct @charleslavon ?

**Comment by thisisjoshford** [comment]
Related: https://github.com/near/near-discovery/issues/765#issuecomment-1808416578

> @heycorwin @thisisjoshford Hot take coming in - we should not do this. Let's partner with Justu, and plan how our onboarding flows should lead to partner tools like DevHub, VSCode, and/or Justsu, instead of spending who knows how long to rebuild this IDE

> @heycorwin @thisisjoshford I think we should separate the `Interactive Documentation` effort away from the effort to `Rebuild the IDE`. My hypothesis is that the former is a more effective way to improve the onboarding experience, and the IDE rebuild is something that we should not do - Rather we should ideate on another way to bridge near.org to a smooth development experience.

I'm 100% in support of collaborating with community members like Jutsu and incorporating them into the onboarding experience. I agree that interactive documentation is a more effective way to improve the onboarding experience and the IDE redesign's main purpose was to support that. 

If we decide to not update the layout of our IDE I see two options here:

1) Update interactive documentation designs to integrate into our existing IDE layout. 
2) Partner with Jutsu and assist in creating interactive documentation with their platform.
