### ISSUE TITLE
Notifications: Push and Regular notifications are not sent for interactions on a post reply

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#668]
**This would be an Enhancement to notications**
When user A posts content on near.org and user B replies. User B does not receive any notifications when someone likes or replies to their reply-comment. 

I posted a reply to Eugene's post [here](https://near.org/s/c?a=charleslavon.near&b=102617264). Then noticed that although my reply had 3 likes, I did not receive any push notifications nor do I see any notice of the likes in the UI at  [near.org/notifications](near.org/notifications) nor [near.social/](https://near.social/mob.near/widget/NotificationFeed)

**Describe the solution you'd like**

1. when user B replies to user A's post, user A should be notified 
2. when user C likes user B's reply, user B should be notified 

**What would it cost ?**
What would it cost to support this 3rd case. 
3. when user C replies to user B's reply, both user B and user A are notified. 

cc @ravigautham @heycorwin

**Comment by heycorwin** [comment]
Agreed that this is the expected behavior. We should just be able to modify the language of existing notification types slightly to accommodate these new ones.
