### ISSUE TITLE
Improve Whitepaper Access on near.org

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#671]
We have a request from Mally, Bowen, and Illia to improve access to whitepapers on near.org so that they are viewable in a better format. Current format results in a poor user experience and new versions of the Protocol and Sharding papers are going to be released by Nearcon.

Requirements:
- We should update all links that begin with near.org/papers/ lead to PDF documents (e.g. near.org/papers/nightshade)
- We should have near.org/papers contain a list of all PDFs
- We should add a section to our main nav header that provides easy access to near.org/papers

**Comment by charleslavon** [comment]
@ravigautham these papers are currently located at https://docs.near.org/concepts/advanced/papers.  How about we add a `Papers` link under [Docs in the new nav](https://github.com/near/near-discovery/issues/677) (cc: @calebjacob @heycorwin ) that points to this link. 

What is it about the current HTML format that causes a poor experience?  I'm open to improving the discoverability of these docs by adding a link within our primary nav, but I don't want us to spend time converting the format of several docs to PDFs.  Do we have specific feedback on issues with the current format? Understanding that might help us find a way to address them with minimal time investment.

**Comment by heycorwin** [comment]
Let's add a link with the label `Technical Papers` under the `Resources` section.

**Comment by ravigautham** [comment]
@charleslavon Mally called out some of the concerns with the current format of the papers on the website in our original slack thread. That was the reason she kicked off the thread. The main issue she called out was that the formatting was really messy and hard for her to read. I think we should circle back on that thread to confirm that this resolves the issue.

**Comment by ravigautham** [comment]
@charleslavon Also I don't believe we ourselves would need to convert these docs to PDFs. I think Mally would provide those  assets.
