### ISSUE TITLE
Unnecessary Flashing as the Activity page loads

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#673]
**Describe the bug**
Both the "NearOS.." marketing homepage and the empty state message "Build your screen..." [flash momentarily as the ActivityFeed loads](https://www.loom.com/share/0262b027924240ea8134d1ccc8ffdb9f). 

**Expected behavior**
Ideally there would be one single loading state that is displayed until enough content is fetched for a contentful render, ala [LinkedIn](https://www.linkedin.com/).  @heycorwin perhaps we need a global loading state or pattern?

**Comment by calebjacob** [comment]
@charleslavon I noticed this when working on the new home page design. I believe I accomplished zero flashing here: https://github.com/near/near-discovery-components/pull/385

We can confirm once everything is published.

**Comment by heycorwin** [comment]
@charleslavon @calebjacob Depending on how widespread issues like this are, we could explore skeleton UI or content loading patterns as part of the DIG. Do y'all know of other instances where performance results in frequent loading states that might benefit from these? If I can get a list then we can see if there's a pattern that might be widely applicable and would help the perception of performance.

**Comment by heycorwin** [comment]
Solving through https://github.com/near/near-discovery-components/issues/405

**Comment by calebjacob** [comment]
My latest performance work on the Activity Page has helped with page flicker, but it's definitely still an issue. I believe our wrapping TOS and NotificationAlert components might be the culprit here. I'll start investigating soon.
