### ISSUE TITLE
Resolve UX issues after recent updates to the primary navigation

### ISSUE THREAD

**Issue by heycorwin** [near/near-discovery#677]
[The most recent changes](https://github.com/near/near-discovery/pull/634) to the primary navigation unfortunately resulted in suboptimal UX after some miscommunication around the intent of the design specification originally provided. This issue provides some suggestions for some simple modifications that result in a more predictable UX.

**Design Spec:** https://www.figma.com/file/Xat7B6X9MB54T6oWxoVPKW/Interim-Navigation?type=design&node-id=127-1734&mode=dev

## Problems
1. The original design spec was created under the assumption that the new navigation pattern would be implemented in concert with updates to the homepage and subsequent website pages. Many of the primary nav items were intended to link to pages internal to near.org. Since the navigation was implemented ahead of the pages themselves, there were several core nav items missing their intended destinations. Rather than omit them, the decision was made to point these to documentation pages. <br><br>Unfortunately, the experience is quite jarring as it is not clear to the user that interacting with them results in being taken out of the experience to documentation pages rather than internal pages that accurately reflect the navigation labels. Additionally, the documentation pages they point to are not consistent in their use of language, resulting in a feeling that the user has been taken to an unrelated destination. _Example: "Decentralized Front-Ends" take the user to a docs page with the title: "Components"_<br>

2. As outlined in https://github.com/near/near-discovery/issues/669, the "Current Component" details were removed from the navigation. This was not an intentional design decision and was rather an oversight. (cc @thisisjoshford @frol)

3. With the new website navigation being implemented _ahead_ of the updated navigation for the NEAR Developer Network (ie the "Logged In" experience), some "Discover" oriented nav items intentionally omitted from the website navigation were subsequently re-introduced in an attempt to address the need from logged in users. Their re-introduction resulted in redundant links between the "Discover" navigation menu and the secondary "Discover" sections within adjacent menus. (cc @TiffanyGYJ)

## Solution

1. Until new page destinations are complete, we should simply omit their respective navigation items (ie the "Platform" menu) so as not to create confusion between inaccurately mapped navigation items and their destinations.<br>

2. Re-introduce the "Current Component" details.<br>

3. Remove redundant links where duplicates exist (ie Remove the secondary "Discover" sections)<br>

4. Some additional refactoring of the "Develop" tab to more accurately map the items contained within to their respective sections in the documentation. Additionally, introduce a "Docs" section header to clearly indicate that these links have destinations located within docs.

<br>
<img width="1408" alt="Screenshot 2023-10-06 at 2 18 51 PM" src="https://github.com/near/near-discovery/assets/5934188/fa2d3355-fc6a-4967-b94b-9b73528ad17b">

**Comment by charleslavon** [comment]
@heycorwin This looks great. Thanks for sharing the context around how we landed on this in-between state with the current nav. 

Am I correct to understand this refined nav as intend for both the "logged out and logged in" views?

**Comment by heycorwin** [comment]
@charleslavon yes. Until we are ready to implement the new dedicated developer network navigation, this can serve dual roles, and we can continue to iterate on this as needed.

**Comment by calebjacob** [comment]
Thanks @heycorwin - this makes a lot of sense. Will get this implemented in the upcoming sprint.
