### ISSUE TITLE
Display platform release notes / what's new?

### ISSUE THREAD

**Issue by thisisjoshford** [near/near-discovery#690]
### Description
Consistent feedback from developers have been lack of awareness to new features that have been shipped. In efforts to help resolve this we can increase user awareness of recent changes made to near-discovery by displaying release notes as they happen. 

Fortunately, we have [existing design work and an example implementation](https://github.com/near/near-wallet/issues/2074) that was created for NEAR Wallet.

### Completion Requirements

- [ ] Determine release notes format & content
- [ ] Create simple landing page for current & archival release notes
- [ ] Create toast notification or similar 
- [ ] Create visible link on near.org to recent updates

### Resources
Previous implementation in Wallet -> https://github.com/near/near-wallet/issues/2074

Example:
<img width="462" alt="Screenshot 2023-10-10 at 4 43 45 PM" src="https://github.com/near/near-discovery/assets/58483342/62d2e270-92f6-4f66-a9d9-5cba8e7aabec">

**Comment by Ishatt** [comment]
Related: https://github.com/near/near-discovery/issues/546

**Comment by charleslavon** [comment]
@thisisjoshford we now have release notes auto created on each production release for near-discovery and near-discovery-components. Perhaps that's good enough for now and this can be closed?

**Comment by thisisjoshford** [comment]
I am happy to close the related issue https://github.com/near/DX/issues/18, but I still think there should be some way of notifying a logged-in near.org user of platform changes/updates. I would argue that a very small percentage of near.org logged-in users subscribe to `near-discovery` releases, and visibility is still low. 

For me its still two parts: 
- [x] create regular releases w/ clear updates
- [ ] surface this information to end users
