### ISSUE TITLE
Provide guidance in the Global Nav for Founders

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#691]
**Problem**
Founders who come to near.org looking for guidance on how to advance their project has lost some discoverability on their best next step due to not having an Global Nav option that speaks directly to them

**Describe the solution you'd like**
Perhaps we add a `Projects` or `Founders` link under Ecosystem (or Discover) which leads to Near Horizon

[additional context](https://pagodaplatform.slack.com/archives/C05UJ24GU3F/p1697025876279959)

**Comment by vanessadespain** [comment]
Thanks for this callout! @ravigautham and I chatted this morning and landed on a solution that I've visualized below and updated our links spreadsheet to reflect. 
<img width="996" alt="image" src="https://github.com/near/near-discovery/assets/8346374/22c26a8e-d04e-4848-bf9f-f360319ab585">


Related we also added a link to Sandbox for greater discoverability in addition to making some minor adjustments to the visual design of the Subheads on the Develop menu to make those labels not appear as links. Pinged directly with Caleb about this as well. 
<img width="928" alt="image" src="https://github.com/near/near-discovery/assets/8346374/501572e2-4dea-4ba1-b839-e13af38a35b2">
<img width="288" alt="image" src="https://github.com/near/near-discovery/assets/8346374/cb123c11-d662-40b3-9189-9b9c26449e84">

[Figma link](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=1324%3A51448&mode=design&t=QN6eN01rEdIISYKq-1)
[Links spreadsheet](https://docs.google.com/spreadsheets/d/1k3AmeyjTrf6FF_QQ8QvLDfmyvV9Kv219kWpJHenYFbU/edit#gid=1299831806)
