### ISSUE TITLE
significant lag when navigating between pages and tabs on mobile

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#693]
**Describe the bug**
I've found that clicking on a link on mobile often requires multiple clicks. It's as if the UI is blocked on rendering the content of the current page before it fully registered that a link has been clicked. 

Notice in this video how the unselect tab label becomes **bold** but still requires an additional click or two before the UI navigations to the selected tab. 

https://github.com/near/near-discovery/assets/1915116/f3a86366-14dc-42f5-953c-cdaf11b0b5cf

**Comment by Sky-De** [comment]
@charleslavon hi there, i would like fix this issue,
Please assign this to me, i will start workiny on this as soon as i get assignment
Thanks
