### ISSUE TITLE
Apply moderation to more near.org surfaces

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#698]
Thus far, moderation has only ever applied to the Feed. It has ever applied to the profile page.  This issue involves adding moderation to the following areas 

1. Apply moderation to ProfilePage (near/widget/ProfilePage): https://github.com/near/near-discovery-components/issues/376
2. Apply moderation to single post and single comment views: https://github.com/near/near-discovery-components/issues/414
3. Block widget feature at gateway or VM level 

[Slack Message](https://pagodaplatform.slack.com/archives/C05CE6QGQRF/p1697123150548299)
```[tasklist]
### Tasks
- [ ] Block widget feature at gateway or VM level
```

**Comment by tidus974** [comment]
Backlogged as discussed here https://docs.google.com/document/d/1jNw0qFMLzi_3xKLmKZDEINxY8omzXF5VedcXCeHh7aQ/edit
