### ISSUE TITLE
Global Nav Styling Refinement opportunitites

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#702]
There are areas where we could polish the navigation style.

![Screen Shot 2023-10-13 at 12 14 19 PM](https://github.com/near/near-discovery/assets/1915116/de6e63a3-39cd-428f-ad28-95d5f0c01065)

1. hover on link does simple underline which feels like basic <a> behavior and not typical internal link behavior, esp in a dropdown menu
2. “Current component” side of the dropdown feels compressed, looking odd
3. Dropdown itself has no border radius, and default shadow, making it feel like it’s grabbed from a default external library
4. Hovering the “near” logo in the nav adds transparency to the logo itself, odd behavior to mess with the near branding like that

**Comment by charleslavon** [comment]
@vanessadespain @calebjacob Thoughts on these suggestions? Might you have any other suggestions for improvements that we should add to the global nav?

**Comment by vanessadespain** [comment]
Appreciate these thoughts! 

1. I prefer the line treatment for clarity. We could adjust away from "underline" and to "border-bottom" to add more control to the appearance. This is the initial design, border bottom may render closer to the intended design in browser.
<img width="186" alt="image" src="https://github.com/near/near-discovery/assets/8346374/e5c85575-f669-46c0-901f-951d0e2b1fd0">

2. I can look at this! We could try to make the component card fit the height of the dropdown. 

3. I have a design QA item addressing this, including the border-radius, the box-shadow properties, and the z-index of the dropdown that's cutting off the shadow at top.

4. I didn't have an interaction design for this, so I can look into this!
