### ISSUE TITLE
Comment Replies are created in an invalid format

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#703]
comments on a comment not showing up 

An attempt was made in [this transaction](https://nearblocks.io/txns/6V5EcCXZ9YAzcrPvRAFkafcTXsuTCerZxGAcgawKCXzZ#execution) to reply to [this comment](https://near.org/near/widget/PostPage?accountId=mike.near&amp;blockHeight=103176559)

It appears that the comment payload is missing a required field `key`

**Comment by charleslavon** [comment]
@gabehamilton is the scope here small enough that you can fit this into next week's with minimal impact to roadmap priorities?

**Comment by gabehamilton** [comment]
Yeah, I would guess it's not too much work to fix.
