### ISSUE TITLE
new near.org landing pages

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#712]
**These changes should not be merged into production until November 8th.** 

[UI Designs](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=1875-93627&mode=design&t=rJbR5Mvkh5NBJdQL-0)
New URLs to be added into the viewer

https://near.org/blockchain
https://near.org/open-web-applications
https://near.org/onboarding
https://near.org/data-instrastructure
https://near.org/data-availability

[Links](https://docs.google.com/spreadsheets/d/1k3AmeyjTrf6FF_QQ8QvLDfmyvV9Kv219kWpJHenYFbU/edit#gid=2145411553)

**Comment by vanessadespain** [comment]
**Design Status update:** 
- Content is being finalized, design is nearly locked. 

**Files:** 
- [Figma](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=1875%3A93627&mode=design&t=GfBqfE2oNo6kEldm-1)

**Notes for Dev:** 
1. Includes updates to both the navigation and the footer to support links to these new "Platform" pages. 
![image](https://github.com/near/near-discovery/assets/8346374/6cbad81a-fe33-452f-bb44-2114eb561687)

2. All links are captured in the [sheet here](https://docs.google.com/spreadsheets/d/1k3AmeyjTrf6FF_QQ8QvLDfmyvV9Kv219kWpJHenYFbU/edit#gid=2145411553)
