### ISSUE TITLE
Feed updates with new comments every 5s

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#740]
Proposed solution: similar to how posts update every 5s in the background (with setInterval), new comments can be fetched and added to the user's feed.

Initial title was: Comments require a page refresh before appearing
When you leave a comment on a post in the feed, it doesn't show up until you refresh the page. This is the same behavior on `<http://near.org|near.org>` - so I don't believe I broke anything there. We should probably implement a fix soon.

[Slack Message](https://pagodaplatform.slack.com/archives/D03EN2WD16E/p1697822742902499)

**Comment by gabehamilton** [comment]
#433 will handle optimistic updates, this Issue will handle updating the feed with new comments.

Proposed behavior:
 The background process that handles updates will check for new comments every 5s. 
 When new comments are received, for each new comment:
   If sort is Latest:
     look through currently displayed posts.
     If that post is being displayed, update its comments collection.
     If not, do nothing
  If sort is Last Commented
     look through currently displayed posts.
     If that post is being displayed, update its comments collection, move it to the top.
     If not, reload posts/comments collection.

**Comment by charleslavon** [comment]
wont' do.
