### ISSUE TITLE
Posting on near.org triggers a full page refresh

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#742]
**Describe the bug**
On near.org on a desktop browser...
1. When creating a new post, if you're on the Following tab, you don't see your new post at all. 
2. If you're on the All tab with Most Recent selected as you create a new post, you eventually see it after the page reloads and some flickering.

**Comment by calebjacob** [comment]
You also won't see the post if you're on the All tab with "Recent Comments" selected.
