### ISSUE TITLE
[Redesign] near.org Component Sandbox

### ISSUE THREAD

**Issue by thisisjoshford** [near/near-discovery#765]
### What

- Redesign the near.org online IDE's user interface.

<img width="1034" alt="Screenshot 2023-10-31 at 9 40 24 AM" src="https://github.com/near/near-discovery/assets/5934188/843246b9-7b03-44a0-aa6a-85e92195e344">

### Why

- Needed for creating v0.2 of developer onboarding, which will include interactive documentation.

### Resources

- [Figma Design](https://www.figma.com/file/qDrSFeKcKkkc6s82uezNyV/Sandbox?type=design&node-id=0%3A1&mode=design&t=Yj1NVQ7kknCupwVN-1)

**Comment by charleslavon** [comment]
@heycorwin @thisisjoshford Hot take coming in - we should not do this UI. Let's partner with Justu, and plan how our onboarding flows should lead to partner tools like DevHub, VSCode, and/or Justsu,  instead of spending who knows how long to rebuild this IDE

**Comment by thisisjoshford** [comment]
> @heycorwin @thisisjoshford Hot take coming in - we should not do this. Let's partner with Justu, and plan how our onboarding flows should lead to partner tools like DevHub, VSCode, and/or Justsu, instead of spending who knows how long to rebuild this IDE

Moving the conversation here: https://github.com/near/near-discovery/issues/657#issuecomment-1809421121
