### ISSUE TITLE
Push Notifications Backend Wrap-up:  Give users the ability to block/unblock receiving push notifications from a specific dApp

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#775]
Adding a new endpoint to notification server that uses subscription URL for auth, and accepts a acountId/dappId to support blocking/unblocking push notifications for that pair

We will implement this blocking per accountId, e.g. globally across all gateways

**Comment by charleslavon** [comment]
hey @ravigautham we've scoped the remaining notifications work down this issue and https://github.com/near/near-discovery/issues/775

**Comment by ravigautham** [comment]
Sounds good @charleslavon! Is this going to be paired with UI work to surface these settings? Or will that be done at a later time? And are we still planning to have our contract team tackle the design enhancements captured in the Fast Follow epic?

**Comment by charleslavon** [comment]
@ravigautham Instead of the dApp toggles, we'll need a new UI for notifications that is similar to this action menu that appears on posts. 
<img width="580" alt="Screen Shot 2023-10-27 at 10 59 32 AM" src="https://github.com/near/near-discovery/assets/1915116/ca845a26-267c-4b1c-b855-7cad111f59da">
