### ISSUE TITLE
FE: Push Notifications wrap-up: Add an option to the notificationList that support blocking a dApp's notifications

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#776]
relates to: https://github.com/near/near-discovery/issues/775

We want to add an affordance to notifications display, that would allow a user to stop receiving specific types of push notifications - regular UI notifications would still work - this is intended as a means to allow a user to prevent potentially spammy push notifications. 

1. The UI to add: an action menu '...' similar to this one that appears on Posts, which includes the option to 'Block'. Upon clicking 'Block' show a Confirm/Cancel modal that asks 'Do you want to stop receiving push notifications for <Likes, Pokes, Follows, Mentions, DevHub etc.>'
2. Also as part of this ticket,  please propose a way to increase the clickable area of the 'View' button. Such that a user can click on any part of the notification (besides the user profile icon) to view the relevant notification, instead of having to click directly on the View button.

<img width="538" alt="Screen Shot 2023-10-27 at 11 01 01 AM" src="https://github.com/near/near-discovery/assets/1915116/ebff17a5-7402-4ce4-bb4f-e5653a6c2fb1">

<img width="925" alt="Screen Shot 2023-10-26 at 10 20 27 AM" src="https://github.com/near/near-discovery/assets/1915116/fd456d27-a762-4e43-bdec-384a33628168">

**Comment by charleslavon** [comment]
@AmmarHumackicSQA  @erditkurteshiSQA  @HarisSQA  please reach out to @milenakrawczyk for an understanding of what I/O the UI will need to trigger when blocking a notification type.

**Comment by erditkurteshiSQA** [comment]
@charleslavon ,
 As for first point, is there any preference to where an action menu `…` should go?

**Comment by charleslavon** [comment]
Good question @erditkurteshiSQA, in the upper right corner of each notification item. SImilar to the placement on activity feed posts
<img width="667" alt="Screen Shot 2023-11-07 at 11 52 34 PM" src="https://github.com/near/near-discovery/assets/1915116/3452cdc5-d22a-45f9-b985-16ad3b0a0c20">
<img width="413" alt="Screen Shot 2023-11-07 at 11 52 21 PM" src="https://github.com/near/near-discovery/assets/1915116/03a925f7-1d59-48e7-be25-2a2ecb4410e1">

**Comment by milenakrawczyk** [comment]
Hey @charleslavon! I checked the notifications sent to charleslavon.near and there is no "like" notification sent to this account yesterday. Moreover, I verified that all the "like" notifications were blocked in accordance with your preferences. Are you sure that you received a notification for this particular account?
