### ISSUE TITLE
Refactor NearOrg/Notifications components to avoid BOS performance anti-patterns

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#779]
Please review [this PR](https://github.com/near/near-discovery-components/pull/429) and [this one](https://github.com/near/near-discovery-components/pull/452), and perhaps sync with @calebjacob to plan how to refactor the [Notifications Components](https://github.com/near/near-discovery-components/tree/develop/src/NearOrg/Notifications) to reduce the loading UIs  as shown here
![notifications_flicker](https://github.com/near/near-discovery/assets/1915116/ea070510-6d7d-49f3-b23f-45aeb1f7d7a4)

**Comment by calebjacob** [comment]
Looks like a big culprit for the slow loading is the waterfall of requests to fetch the details of each account to render their avatar and display name and fetching a timestamp for TimeAgo. I wonder if Query API would be helpful here to provide all of the profile info and block timestamp for each notification @gabehamilton?

**Comment by gabehamilton** [comment]
Yes, we need to write an Account Indexer (for use in the main feed as well) then we could create a View over the `notifications` and accounts tables. Timestamp we would probably want to add to [notifications](https://near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=dataplatform.near/n0&view=editor-window)

**Comment by shelegdmitriy** [comment]
I'll add [this](https://github.com/near/near-discovery/issues/779#issuecomment-1783216022) as subtask for account indexer task #855

**Comment by shelegdmitriy** [comment]
The usage of account_indexer_v1 will be as part of this task https://github.com/near/near-discovery/issues/855
