### ISSUE TITLE
Gateway level whitelist for transaction signing

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-discovery#787]
**Is your feature request related to a problem? Please describe.**
When user starting to interact with gateway, they see transaction confirmation windows which are extremely confusing to the new users. Especially it's true for ToS confirmation, as it's the first thing every user needs to go through.

**Describe the solution you'd like**
Gateway specifying set of components that are whitelisted and don't require additional confirmation by the gateway to submit transaction. This should be a config that any gateway operator can configure.

For example for near.org it should whitelist all components by account "near".

**Describe alternatives you've considered**
User specific whitelist is also possible that is persistent between different gateways and sessions.

**Additional context**
<img width="1134" alt="Screenshot 2023-10-31 at 4 24 40 PM" src="https://github.com/near/near-discovery/assets/175486/a9599db7-850b-4d6c-992e-11d86fc6699b">

**Comment by calebjacob** [comment]
I've opened a PR to introduce the necessary changes in the VM: https://github.com/NearSocial/VM/pull/160

Once these changes are approved and merged, I'll open another PR on the gateway to enable these new features.
