### ISSUE TITLE
Random execution error appearing in place of components on localhost

### ISSUE THREAD

**Issue by Patrick1904** [near/near-discovery#797]
Execution errors appear randomly in place of components when running near.org locally. One example is the "current component" in the "Develop" menu dropdown:

<img width="1403" alt="Screen Shot 2023-11-02 at 3 19 20 PM" src="https://github.com/near/near-discovery/assets/24921205/297e677c-f4bb-4fc3-88d6-fac2c587735f">

**Comment by charleslavon** [comment]
I suspect this is an issue with your local cache. Have you tried recreating node_modules? Are you referencing an older version of nearsocial/vm?
