### ISSUE TITLE
Replies associated to Moderated Content should still be visible

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#805]
Another edge case to consider. For now if a post is moderated (self or by moderators), it will generally not appear anywhere - including all of it's comments. If we want those comments to still appear (at the post url and/or in the feed) as comments below a UI that indicates  'this post is moderated/unavailable" 
[Slack Message](https://pagodaplatform.slack.com/archives/C05CE6QGQRF/p1699054859497309)

**Comment by tidus974** [comment]
Why would we want to conserve the replies when the post has been taken down? 
From a UX people would miss the context as well right?

**Comment by charleslavon** [comment]
@tidus974 maybe we don't.  As someone who replies on a post that was later moderated, do we want to provide any UX to them besides making their reply disappear?
