### ISSUE TITLE
"View Source" redirects users to "Code diff" instead of actual current version of the code

### ISSUE THREAD

**Issue by frol** [near/near-discovery#814]
**Describe the bug**

Open any component "view source": https://near.org/near/widget/ComponentDetailsPage?src=near/widget/DIG.OverviewPage&tab=source

See the "diff" instead of the actual code:

<img width="1584" alt="image" src="https://github.com/near/near-discovery/assets/304265/6531eaa2-1479-44bd-b826-191e835bdad3">

**Expected behavior**

Previously there was a normal "view source" page that only showed the actual code.

https://near.social/mob.near/widget/WidgetSource?src=near/widget/DIG.OverviewPage

**Additional context**

It was discussed offline with TIffany that it needs to be brought back.

**Comment by charleslavon** [comment]
@charleslavon  link the sidebar width issue here so we can tackle at the same time.
