### ISSUE TITLE
Create UI shows group details and posts

### ISSUE THREAD

**Issue by milenakrawczyk** [near/near-discovery#846]
Create UI that shows group details and posts similar to this widget: https://near.org/near/widget/ComponentDetailsPage?src=mob.near/widget/N.Group&tab=source. Passing to this page an NFT's contractID as the groupId query param should render a page similar to this one: https://near.org/mob.near/widget/N.Group?groupId=v0.8bityonce.near.

The page should have the info about how to join a group: 

![Image](https://github.com/near/near-discovery/assets/66628214/26bea1ff-344d-4617-b7b0-952c805eebf9)

The API will be provided by the groups indexer.

Proposal: https://github.com/NearSocial/SEPs/pull/2/files

**Comment by charleslavon** [comment]
@heycorwin for this groups UI task, we could begin by forking mob's nearsocial components and revamping them with near.org styles and components, or we could jump towards creating the designs that you demo'd in the style of the devnetwork. What do you suggest?
