### ISSUE TITLE
Create UI that supports creating a group

### ISSUE THREAD

**Issue by milenakrawczyk** [near/near-discovery#848]
Create UI that supports creating a group by providing an NFT contract ID.

Proposal: https://github.com/NearSocial/SEPs/pull/2/files

**Comment by charleslavon** [comment]
Similar question here @heycorwin  ... we could begin by forking mob's nearsocial components and revamping them with near.org styles and components, or we could jump towards creating the designs that you demo'd in the style of the devnetwork. What do you suggest?
