### ISSUE TITLE
Create an account indexer

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#855]
`accounts` indexer is already created. ~We still need to publish it under dataplatform account~ and collect historical data. We need to collect all the components we can refactor with `accounts` indexer.

- [x] Use `accounts` indexer for Notifications. Check this task for the context https://github.com/near/near-discovery/issues/779
- [x] Use `accounts` indexer for posts feed

**Comment by gabehamilton** [comment]
#427 needs a tags field on the account indexer.

**Comment by charleslavon** [comment]
@shelegdmitriy it would be helpful to know an estimated effort level for this task. Is this more likely to be a 1,2,or 3 sprint effort?

**Comment by shelegdmitriy** [comment]
> @shelegdmitriy it would be helpful to know an estimated effort level for this task. Is this more likely to be a 1,2,or 3 sprint effort?

We (@gabehamilton and me) have updated the `accounts` indexer and from now it has all the fields related to profile account. In my opinion it's possible to complete in 1 sprint.
