### ISSUE TITLE
idOS loop, error toast, and duplicated informational toasts

### ISSUE THREAD

**Issue by mpeterdev** [near/near-discovery#865]
**Describe the bug**
I tried to go through idOS setup and I end up in a loop

**To Reproduce**
A few minutes prior to this recording, I went throught the initial idOS registration flow. This is subsequently trying to load the settings page after that had been completed

https://github.com/near/near-discovery/assets/24904709/6d1c9492-aa39-41d1-bbe3-db57656dc10e

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.1.1
 - Browser Arc (chromium)
 - Version 1.17.2

**Comment by charleslavon** [comment]
@mpeterdev do you recall what wallet you were using when you found this issue?

**Comment by mpeterdev** [comment]
> @mpeterdev do you recall which wallet you were using when you found this issue?

I believe it was MyNearWallet but not 100% sure
