### ISSUE TITLE
Propose a mechanism to remove/block users from a group

### ISSUE THREAD

**Issue by milenakrawczyk** [near/near-discovery#881]
Propose a mechanism that allows for user removal or blocking within a group.

**Comment by gabehamilton** [comment]
For the 'indexing blocked users' solution, who can report and who can moderate?
With NFT groups it seems like we have two sets of people: the creator of the NFT contract and holders of the NFT. If the contract or NFT collection is created through Mintbase, Paras, etc then the creator of the collection may not have access to the contract.

**Comment by gabehamilton** [comment]
The Moderation features work along similar lines. They could probably be updated to handle groups, there's even a group field already for organizing reports and decisions.
https://near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=dataplatform.near/moderation

**Comment by milenakrawczyk** [comment]
@gabehamilton Thank you for the feedback. As far as I understand only the owner can access the contract according to the Mintbase docs: https://docs.mintbase.xyz/creator/faq#what-is-a-mintbase-contract. However, the way this contract/account could be accessed (and if it can be accessed directly) should be investigated further - if it's possible to access a private key or whether the access is limited to Mintbase UI only.
Using moderation sounds very reasonable. Is it possible to set a moderator for a given account?
