### ISSUE TITLE
iDOS UX Enhancements

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#885]
**Goal**
Update near.org to use idos-sdk v0.0.28 and reduce the number prompts for a user to sign a message, along with the updates outlined here-TBD link from @xuan-ytr

**Comment by xuan-ytr** [comment]
@charleslavon design ready for review for case 1: [Figma](https://www.figma.com/proto/tub847jdGUsekBXok7gAjs/idOS-settings-redesign?page-id=7%3A8&type=design&node-id=8-7410&viewport=-1609%2C-803%2C1&t=GadMGj1gfIzvjvZT-1&scaling=min-zoom&mode=design)

1. Improve user experience for first time visitors on settings page

- Orient users to how to engage with identity & data privacy tab
- Reduce number of prompts

This is a 90% design that has room for feedback from engineering, please provide feedback if there are any feasibility concerns or ideas for improvement.
