### ISSUE TITLE
A notification with long horizontal content can offset the UI display

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#908]
**Describe the bug**
When a notification is received that references a post with a large amount of content, the horizontal content is not clipped, causing the text on the near.org/notifications to overflow. 

**To Reproduce**
It's probably easiest to repo by using two near accounts
1. From account A, create a post with a large amount of content, e.g. [the this post](https://near.org/s/c?a=efiz.near&b=109272149)
3. From account B, reply to the above post and mention account A. 
4. From account A, go to near.org/notifications on mobile and on a desktop client

The UI becomes misaligned due to the text overflow

**Desktop**
<img width="1434" alt="Screen Shot 2024-01-08 at 9 44 05 AM" src="https://github.com/near/near-discovery/assets/1915116/629cb301-69bd-484c-8afe-e95d6cf9f5ea">

**Mobile**
![mobile](https://github.com/near/near-discovery/assets/1915116/b440c700-1264-401f-9b2c-e622d313507a)

**Comment by amirsaran3** [comment]
I couldn't reproduce bug. Must be solved already.

This is how it looks in local development:
![Image](https://github.com/near/near-discovery/assets/95852708/725cf5c4-35c2-4117-89ef-dede00fc5c20)

**Comment by charleslavon** [comment]
@amirsaran3 try to reproduce this in production on near.org. Looking at the PRs which have been merged since the latest release, this issue does not appear to have been fixed.

**Comment by erditkurteshiSQA** [comment]
Hi @charleslavon
Can you please take a look at this PR: https://github.com/near/near-discovery-components/pull/617.
We managed to reproduce this bug and I think it was because of the link tag.
Should be a rare case but we added a fix for that.

**Comment by charleslavon** [comment]
@erditkurteshiSQA the preview looks good! Appreciate your persistence
