### ISSUE TITLE
Notification content doesn't match the action that occurred

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#909]
**Describe the bug**
1. A notifications for a like on a Post of type Comment/Reply is displayed with a link to an incorrect post and incorrect post preview. 

In [this transaction](https://nearblocks.io/txns/3ab8q7Py7SRdPYDxzCWSDRBd26xzKSxod8XZaYPvpRT5#execution) I replied to [this post ](https://near.org/near/widget/PostPage?accountId=efiz.near&blockHeight=109213710). The post's author liked my comment and also mentioned me in a reply to my comment.  I should've received a like notification and a mention notification. I correctly received the mention notification, but the like notification came as a `mention` with a link to a post that includes no mention. 

<img width="977" alt="Screen Shot 2024-01-08 at 10 05 03 AM" src="https://github.com/near/near-discovery/assets/1915116/f57bd468-4098-45ed-8523-f1e7034699de">

2. Push notifications for a `like` are received as a `reply`. This screenshot shows the push notifications received via HERE wallet and near.org. HERE correctly shows both notifications types, Near is representing the `like` as a `reply`

![978](https://github.com/near/near-discovery/assets/1915116/c805d7c7-2987-4fb8-84ef-2de818b6e1e5)

**Comment by shelegdmitriy** [comment]
The `#1` item from the description should be resolved. The problem was with missing relationship in the table from which we fetch the data. @gabehamilton added such a relationship and everything works

**Comment by shelegdmitriy** [comment]
I'm not sure, but the `#2` should be resolved too. But, so far I can't confirm this and I'd like to wait a bit before push notifications will start to work well
