### ISSUE TITLE
Session is lost when signing in with MyNearWallet

### ISSUE THREAD

**Issue by calebjacob** [near/near-discovery#910]
**Describe the bug**
When signing in with MyNearWallet, your session is lost and you're signed out when refreshing the page. Other wallets like Nightly do not have this issue.

**To Reproduce**
1. Go to `near.org`
2. Sign in with `MyNearWallet`
3. See that you are signed in
4. Refresh the page
5. See that you are no longer signed in

**Expected behavior**
User should remain signed in after refreshing the page.

**Comment by mpeterdev** [comment]
![Screenshot 2024-01-08 at 11 28 34 AM](https://github.com/near/near-discovery/assets/24904709/2936b804-cd79-4186-a5b8-c892727bc3f3)

I am wondering if this incorrect value in localstorage after signing in may be the culprit
