### ISSUE TITLE
Near Social seems to be using an old version of Wallet Selector libs

### ISSUE THREAD

**Issue by lostpebble** [near/near-discovery#916]
Hi, I work on the Meteor Wallet project.

**Describe the bug**
We noticed today that the critical update we made about a month ago (https://github.com/near/near-discovery/pull/877#issuecomment-1845277520) was somehow reverted recently due the dev VM being out of sync with the production VM, and the dev VM being used as the main driver (I'm not too sure, I'm just going by the commits I see, e.g. https://github.com/near/near-discovery/commit/874b2017f03b9af4d2855e7c09e03c7897054573 , https://github.com/near/near-discovery/commit/3b7747bba95cab6d016465b9efba9a78ecb9d6dd)

We noticed this by viewing the executed code in the browser- the error message that is being thrown is not one that exists in the newer version of our Wallet Selector package. It is the error that was fixed last month.

**To Reproduce**
1. Go to Near Social
2. Sign in with Meteor Wallet
3. Try and do an action which requires the wallet to open (a transaction)
4. See error in console

**Expected behavior**
The fix we deployed is actually being used.

**Screenshots**
This is the old code error, which is currently being thrown on Near Social:
![image](https://github.com/near/near-discovery/assets/1508863/6e3483e7-41da-4b66-aab1-57e10f6ef776)

Please could we resolve this ASAP, as we are about to deploy Ledger support and this is preventing us from proper testing on Near Social, as well as preventing our users from interacting with the platform.

**Comment by erditkurteshiSQA** [comment]
Hi @lostpebble 
Thank you for reporting the issue.

After thorough attempts, we could not reproduce the issue on near social.
If you encounter it again or have additional details, please let us know or update the issue.

**There is a new currently open PR for a new wallet-selector 8.9.2.**

**Comment by lostpebble** [comment]
Hi @erditkurteshiSQA - thanks for taking a look. I'm hoping the new release of Wallet Selector now will resolve all these issues.

Strange that it can't be reproduced, as the error message being thrown on my end was definitely only in the older version of our SDK. The error was thrown when I tried to withdraw my storage bank from Near Social. But with the new updates, should be resolved as well as a few other things which needed fixing.
