### ISSUE TITLE
http error 500 logging & monitoring 

### ISSUE THREAD

**Issue by jinouyang** [near/near-discovery#919]
**Is your feature request related to a problem? Please describe.**

**Request:** integrate error logging on near.org log http error 500 and its properties. See below for examples of errors.

**Questions that could be answered with the error loggings:**
- How frequently does the error occur and what types of error they are? 
- Does the same error reoccur from time to time and makes it an unreliable experience for users & developers? 
- Are the errors specific to any gateway / browser / device / release / etc. (for debugging purpose)? 
- How quickly are the errors resolved? 

**Describe the solution you'd like**
1. Address web engine dependency 
2. Integrate monitor toolings like https://sentry.io/welcome/ to log 500 error and its properties (instead of building entire monitoring framework in house)

**Describe alternatives you've considered**
- https://opentracing.io/  if this type of vendor partnership raises concern 
- But my counter argument to this ^ is: it's better to have something integrated in a less ideal way than not implementing it at all because we can't find a solution that makes everyone happy

**Additional context**
Some screenshots of the http error 500 that could happen on gateways:
Jan 8th:
<img width="1696" alt="image" src="https://github.com/near/near-discovery/assets/92119687/b10a134a-8271-4ddc-a545-b256bdc6f859">
Jan 10th:
<img width="1777" alt="image" src="https://github.com/near/near-discovery/assets/92119687/d92f0299-f281-46c7-a8ee-2693343d7fa1">

**Relevant VM errors:** 
- vm [source code error code](https://github.com/NearSocial/VM/blob/7f2cfb9580462686bced3547cdceddf9b865ffbf/src/lib/components/Widget.js#L147)
- in addition to the source code error, VM could also throw errors when someone is building components incorrectly. This might also worth logging to understand common obstacles of developers.

**Other considerations**
- 400 code might also worth logging but it might be noisy and difficult to make use of at this stage of the product

thanks @roshaans for the VM and component developer context

**Comment by jinouyang** [comment]
**Update:** 
We are changing the scope of this issue to adding monitor on "Source code" error only. 

**More context:**
- Not all handled errors worth monitoring / worth the manual effort of adding them 
- Source code errors happen quite frequently on the website and created bad user experience 
- The source code errors could be caused by (1) out of sync social indexer or DB (2) the code / user could've entered an invalid widget path (3) an issue with gateway problem e.g. trying to render a mainnet component while calling a testnet rpc. A spike in this error will indicate an indexer or gateway problem. 
- More service is being moved to our query api indexers, which will have their own alerting mechanism to let us know when they are failing or significantly out of sync with block height

cc. @charleslavon

**Comment by charleslavon** [comment]
hey @jinouyang I've increased the scope here a bit. We've added reporting for [all handled handled errors](https://github.com/near/near-discovery/pull/953) on near.org. It's live on beta.near.org and will deploy next week.   There's also two in review PRs which add error reporting for a set of [VM handled errors](https://github.com/NearSocial/VM/pull/175)

**Comment by charleslavon** [comment]
Re-opening. We're awaiting a new nearsocial/vm release (probably in a couple weeks), then we can update to the latest VM and start receiving their indications of error
