### ISSUE TITLE
Connect Rudderstack Analytics to docs.near.org

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#930]
- Create a new rudderstack source & api key
- create a similar [analytics.ts](https://github.com/near/near-discovery/blob/aef946d351826459222359f76d58e9bb9752689c/src/utils/analytics.ts#L4) integration into docs.near.org
- verify data is piped through the two enabled transforms 
- ensure data is piped into the DL Prod destination.

**Comment by s-n-park** [comment]
Question from Charles: What destination should this be sent to?

Same as previous near.org setup

**Comment by s-n-park** [comment]
This ended up getting resolved on its own
![image](https://github.com/near/near-discovery/assets/146785798/e6a691bf-bd45-4b74-ae07-29ac485cae87)

Note for later that we're not tracking clicks/mouseovers/etc. - just page events

**Comment by charleslavon** [comment]
@s-n-park tracking @ https://github.com/near/docs/issues/1699
