### ISSUE TITLE
Add Polygon Logo to Data Availability website page (https://near.org/data-availability)

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#931]
Polygon Logo should appear in the center of the list of all logos, we should also move the Arbitrum logo towards the center of the list. Logo is attached below

![polygon_black](https://github.com/near/near-discovery/assets/129213007/20f54cd0-838f-4c4b-8ad1-3663d839e996)

**Comment by jackson-harris-iii** [comment]
@ravigautham  is there a specific url we would like the logo to link to or is the main polygon website okay?
