### ISSUE TITLE
[Page update] Update Data Availability page

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-discovery#944]
**Is your feature request related to a problem? Please describe.**
Currently DA page doesn't provide clarity of partners and their status, no link to more content and news

**Describe the solution you'd like**

At the top under "Simplify and lower ..." let's add CTA buttons (similar to what we have at the bottom right now) "Read docs" and "Get updates" and "Intro to NEAR DA" linking to  https://pages.near.org/blog/why-near-data-availability/

Have clear categories of partners and consider moving it before technical diagram:
 - Frameworks -- should link to how to use this specific framework with NEAR DA
    - Arbitrum, Polygon, Starknet, Movement, Fluent
 - Rollups-as-a-Service - should link to the rollup itself
    -  AltLayer, Caldera, Dymension, Zeeve, Vistara
 - Rollups - link to rollups page
    -   [Web3Game](https://web3games.com/)

At the bottom where CTA buttons are - let's add link to https://pages.near.org/blog/why-near-data-availability/ as a button "Intro to NEAR DA"

Link to articles and videos about near DA.

**Comment by ravigautham** [comment]
Adding carousels on the page that features the newest blog posts and relevant Twitter posts related to NEAR DA.

**Comment by samwangnf** [comment]
Arbitrum technical docs are still missing from https://docs.near.org/data-availability/integrations.

Firat mentioned docs team was supposed to add last week, but it's still missing.

**Comment by shelegdmitriy** [comment]
Hey @ilblackdragon! What is the links for "Gateway" and "Web3Game"? Seems like we don't have some on the page so far. Maybe "Gateway" means [Mantle Gateway](https://bos.fusionx.finance)?

**Comment by ravigautham** [comment]
@ilblackdragon We've been building a cost-savings dashboard (nearmodular.com) to illustrate the benefits of NEAR DA vs competitors. We want to incorporate this with the near.org data availability page. I think we should take a step to revisit the holistic design of the page to make sure it has a better flow. I'm happy to take lead on this and collaborate with Vanessa.
