### ISSUE TITLE
[Page update] Home page updates

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-discovery#945]
**Describe the solution you'd like**
Home page needs next updates.

Title: Chains Abstracted.
Sub-title: NEAR is the chain abstraction stack, allowing to seamlessly build applications that scale to billions of users and all blockchains

Update partners: add Google, Alibaba, also Polygon, EigenLayer, Arbitrum, Optimism

**Comment by nearlyalmonds** [comment]
Suggested light edit to copy:

Title: Blockchains, Abstracted.
Subtitle: NEAR is the chain abstraction stack, empowering builders to create apps that scale to billions of users and across all blockchains.

**Comment by charleslavon** [comment]
hey @vanessadespain or @heycorwin can you please point me towards, or create, icons for Google, EigenLayer, and Alibaba which are of a similar format to those displayed @ https://near.org/da

**Comment by vanessadespain** [comment]
Hey @charleslavon — I pulled those logos, resized, and dropped them [here for you](https://drive.google.com/drive/u/0/folders/1AI3TszJR4ar44q4k3ZeX1k4Vms24iZQk)

**Comment by vanessadespain** [comment]
RE: Logos

Are these logos all of a similar nature? For instance are they all partners where NEAR is providing a service to them? I'd recommend we curate this list down to 6-7 for the most impact and readability.

**Comment by charleslavon** [comment]
Here's how it looks with all icons. One needs to discover the horizontal scroll to see them all; similar to the `/da` page.

![home](https://github.com/near/near-discovery/assets/1915116/cfe26a46-fd72-43ae-bd26-c0ad3d881d3c)

**Comment by charleslavon** [comment]
@vanessadespain when you get time, please also format [this logo](https://drive.google.com/drive/folders/1Kyo8OFKH3uGkTRPtU0lEbw1nPMYU-xHa) for the da page

**Comment by vanessadespain** [comment]
Got ya! I added it to the same Drive folder

**Comment by ilblackdragon** [comment]
We should not do horizontal scroll. (and on /da we should split into categories)

We can remove few and bring them closer. Or put them into 2 lines.
