### ISSUE TITLE
🔷 [Epic] Case studies

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-discovery#946]
**Describe the solution you'd like**
We need to add case studies to the near.org

There will be different categories, like Loyalty, Gaming, Finance, Payments, etc.

Under each category, you want to see a highlight of specific project, video testimony of the founder, link to source code or other way to get started. And list of other projects that are in this category building with NEAR.

This should be easily accessible from Build top menu. Ideally case studies are directly accessible from the drop down menu.

**Comment by charleslavon** [comment]
NF marketing has included this in their designs and will own implementation
