### ISSUE TITLE
🔷 [Epic] Remove wordpress

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-discovery#948]
## What ?

- **High Level Goal:**

Remove usage of wordpress on near.org

## Why ?

- **Background:**
 
Currently wordpress pages lead traffic away and hurt SEO. They are also not using the benefits of NearJS limiting the experience

---

## How ?

- [ ] #943 
- [x] #947
- [x] Static pages
```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/1047
```

**Comment by charleslavon** [comment]
- Near.org/blog is no longer a iframe embedded wordpress page. This UI is now static html files auto-exported from wordpress and served by near.org directly. The search indexing of blog contents will now be attributed near.org.  
- near.org/events is also no longer iframe embedded wordpress content. Dima completed the integration with NF's events content management tool - Luma. 

	- With the above two complete, we've done enough work towards deprecating wordpress content from near.org and won't put additional effort here. The remaining wordpress tech debt is enumerated @ https://docs.google.com/spreadsheets/d/1MOym825Z6t7Pii3Ng72nf3oPcw4m3bdO9NmB3gELp20/edit#gid=0
