### ISSUE TITLE
🔷 [Epic] Navigation Updates

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#955]
## What ?

- **High Level Goal:**
Based on the click through rates of our navigation items, there's room to improve such that users can find their desired information and destinations more easily. 

![image (12)](https://github.com/near/near-discovery/assets/1915116/ef68f44c-e65a-401d-9886-1f5df36e083b)

- **UX Designs:**

In progress
---

## Why ?

- **Background:**

1.  CTRs on navigation menu links [are lower than expected](https://pagodaplatform.slack.com/archives/C059R4THKL7/p1706115997758879?thread_ts=1706035418.079559&cid=C059R4THKL7).

- **Move the Needle:**

1. Improve the CTR of near.org visitors to value-add destinations

---

**Comment by vanessadespain** [comment]
For a first launch iteration we've put together this direction which maintains the current structure, removes all direct-to-docs links under Develop, adds a link to DevHub. 
<img width="2121" alt="Nav Approach for February 2024" src="https://github.com/near/near-discovery/assets/8346374/a757c969-430c-4966-8b9f-5e7d3dfb6b12">
This should be considered a first iteration on a path to optimization with the plan to continue making improvement as we see the data come in, update existing pages, and add new pages. 
[Figma link for dev implementation](https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=434%3A19547&mode=dev&t=iUc65UKqq5bvbzRC-1)

**Comment by s-n-park** [comment]
Updated click rates + mouseover can found [here](https://github.com/near/data-analytics/issues/73)
