### ISSUE TITLE
Blog Post MVP

### ISSUE THREAD

**Issue by thisisjoshford** [near/near-discovery#966]
### Objective: 

```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/992
- [ ] https://github.com/near/near-discovery/issues/993
- [ ] https://github.com/near/near-discovery/issues/994
- [ ] https://github.com/near/near-discovery/issues/995
```

**Comment by vanessadespain** [comment]
Based on this directive I made a few screens demonstrating the core user flow: 
![image](https://github.com/near/near-discovery/assets/8346374/ae262329-8da5-4ef6-be8c-0ff3fd090f6f)
[In Figma Here](https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=468%3A46957&mode=design&t=RyeeYvg8q34gNzC7-1)
