### ISSUE TITLE
Improve "Sign In" screen to avoid users' confusion

### ISSUE THREAD

**Issue by frol** [near/near-discovery#970]
**Describe the bug**

Login screen is confusing to users:

<img width="581" alt="image" src="https://github.com/near/near-discovery/assets/304265/f7e5fb6b-bda8-4145-b0d3-e56fa2289081">

Every single time I see users using this screen, they get confused by it. If they have a wallet, they still enter their email, but more often than not, they enter email and click "continue with wallet" without actually having a wallet.

**To Reproduce**

1. Go to https://near.org/signin
2. Get confused by two primary buttons

**Expected behavior**

I would suggest to clarify that there are two options, like in old good web:

<img width="476" alt="image" src="https://github.com/near/near-discovery/assets/304265/fea14b8c-e08f-444b-b8b9-4b2301302c30">

**Comment by nall-near** [comment]
There is already a new design for this planned:
https://www.figma.com/file/oK9aMWVmjoXHRUcBUFmFvT/Onboarding?type=design&node-id=4178%3A164637&mode=design&t=hzX9SPVGG5S8beb1-1

**Comment by thisisjoshford** [comment]
Looks like https://github.com/near/near-discovery/pull/929 resolves this issue and uses your design @nall-near. 
[
Here is a preview of the PR](https://near-discovery-git-update-put-sig-aa25aa-near-developer-console.vercel.app/)
