### ISSUE TITLE
Adjust Like & Comment such that they funnel logged-out users to create an account

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#992]
- a logged out user views a blog post 
- they click on Like or Comment (currently the button is disabled)
- this triggers the [fastAuth sign-up modal](https://github.com/near/near-discovery/pull/929)
- upon account creation (whether via fastAuth or wallet connection) the user is redirected back to that same blog post

**Comment by s-n-park** [comment]
FYI in case it's helpful - number of likes/comments for NEAR social daily is low hundreds. I'd assume Blog likes/comments would be some subset of that

![Image](https://github.com/near/near-discovery/assets/146785798/1ed919f7-df36-42a1-8225-a9118c9c62a0)

From [Dash](https://4221960800361869.9.gcp.databricks.com/sql/dashboards/08842a87-24dc-40f4-b1a0-e9a90dc022f6?o=4221960800361869)

**Comment by jackson-harris-iii** [comment]
@charleslavon this issue was closed by https://github.com/near/near-discovery-components/pull/673. However I think the changes made to use the modal is impacting the desired experience. Here is a quick video for reference: https://www.loom.com/share/8996f5ff9d6c48d8b2e4e04712a7fef0?sid=bc2e8978-8739-4f2f-8d1b-8a5603aedb08 thoughts on how to proceed here?

**Comment by charleslavon** [comment]
hey @jackson-harris-iii Let's trigger the new signin/signup modal, to allow users to authenticate with the modal/wallet and get redirected back to this page (instead of going to the applications page).  You may want to pass the a reference to [this hook](https://github.com/near/near-discovery/blob/068fd184c0abb6fa50d994f73d28a202f41c516b/src/components/navigation/desktop/DesktopNavigation.tsx#L128) to the like/comment buttons.

**Comment by jackson-harris-iii** [comment]
> hey @jackson-harris-iii Let's trigger the new signin/signup modal, to allow users to authenticate with the modal/wallet and get redirected back to this page (instead of going to the applications page). You may want to pass the a reference to [this hook](https://github.com/near/near-discovery/blob/068fd184c0abb6fa50d994f73d28a202f41c516b/src/components/navigation/desktop/DesktopNavigation.tsx#L128) to the like/comment buttons.

The blogPostPage is a bos component, so I currently don't have access to the hooks used in the near discovery repo. 🤔

**Comment by charleslavon** [comment]
@jackson-harris-iii is that a blocker? can the required functions be passed into the bos components from the gateway?
